/* don't edit, auto generated by tools/toolchain.py */

#ifndef __YOC_CONFIG_H__
#define __YOC_CONFIG_H__
#ifndef CONFIG_CPU

#define CONFIG_DEBUG 1
#define CONFIG_CHIP_NAME "sc5654"
#define CONFIG_CHIP_VENDOR_STR "silan"
#define CONFIG_SYSTICK_HZ 1000
#define CONFIG_CHIP_SC5654A 1
#define CONFIG_NUTTXMM_NONE 1
#define CONFIG_CLI 1
#define CONFIG_NON_ADDRESS_FLASH 1
#define CONFIG_CPU_CK803EF 1
#define CONFIG_SOFTWDT 1
#define CONFIG_DEVICE_NAME "devicename"
#define CONFIG_BOARD_NAME "cb5654"
#define CONFIG_CHIP_NAME_STR "sc5654a"
#define CONFIG_DEVICE_TYPE "devtype"
#define CONFIG_PARAM_NOT_CHECK 1
#define CONFIG_ARCH_CSKY 1
#define CONFIG_KERNEL_NONE 1
#define CONFIG_VENDOR_NAME "csky"
#define CONFIG_CPU "ck803ef"
#define CONFIG_ARCH_INTERRUPTSTACK 512
#define CONFIG_SPIFLASH_DRV 1

#endif
#endif
