#!/bin/sh

MK_GENERATED_PATH=generated

CUR_SOLUTION_PATH=$SOLUTION_PATH
CUR_BOARD_PATH=$BOARD_PATH
mkdir -p $MK_GENERATED_PATH

CONFIG_LDF=${CUR_BOARD_PATH}/configs/gcc_flash.ld
echo $CONFIG_LDF
cp ${CONFIG_LDF} ${CUR_SOLUTION_PATH}/
