#! /bin/env python

from yoctools import Make

defconfig = Make(elf='boot.elf', objcopy='boot.bin', objdump='boot.asm')
# defconfig = Make(elf='boot.elf', objcopy='generated/data/boot')

Export('defconfig')

defconfig.build_components()