Import('env')
src = [
    'qspi_flash/lsqspi.c',
    'qspi_flash/spi_flash.c',
    'uart/uart.c',
    'cache/lscache.c',
    'trng/lstrng.c',
    'ecc/lsecc.c',
    'crypt/lscrypt.c',
    'iwdt/lsiwdt.c',
    'adc/lsadc.c',
    'timer/lstimer.c',
    'rtc/rtc.c',
    'uart/smartcard.c',
    'dma/dma.c',
    'pdm/dmic.c',
    'spi/lsspi.c',
    'spi/lsi2s.c',
]

if env['IC'] != 'taurus':
    src += ['calc/calc_div.c',]

inc = [
    'qspi_flash',
    'cache',
    'calc',
    'uart',
    'trng',
    'ecc',
    'crypt',
    'iwdt',
    'adc',
    'timer',
    'rtc',
    'dma',
    'pdm',
    'spi',
    '.',
]
src_files = File(src)
inc_dirs = Dir(inc)

Return("src_files","inc_dirs")