/* don't edit, auto generated by tools/toolchain.py */

#ifndef __YOC_CONFIG_H__
#define __YOC_CONFIG_H__
#ifndef CONFIG_CPU

#define CONFIG_CHIP_CH2201 1
#define CONFIG_CHIP_NAME "ch2201"
#define CONFIG_TEE_CA 1
#define CONFIG_CLOUDIO_ALIMQTT 1
#define CONFIG_DEBUG 1
#define CONFIG_BOARD_NAME "cb2201"
#define CONFIG_ARCH_CSKY 1
#define CONFIG_CLI 1
#define CONFIG_VENDOR_NAME "csky"
#define CONFIG_KERNEL_RHINO 1
#define CONFIG_CPU_CK802 1
#define CONFIG_ARCH_INTERRUPTSTACK 1024
#define CONFIG_CPU "ck802"

#endif
#endif
