
## 第一部分： 基础信息
name: iot_miniapp_ui_demo                       # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.1                                  # <必选项> 组件版本号
description: iot_miniapp_ui_demo                # <必选项> 建议至少20字以上
type: solution                                    # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
