/*
 * Copyright (C) 2017-2020 Alibaba Group Holding Limited
 */

/******************************************************************************
 * @file     soc.h
 * @brief    CSI Core Peripheral Access Layer Header File for
 *           CSKYSOC Device Series
 * @version  V1.0
 * @date     7. April 2020
 ******************************************************************************/

#ifndef _SOC_H_
#define _SOC_H_

#include <stdint.h>
#include <csi_core.h>
#include <sys_clk.h>

#ifdef __cplusplus
extern "C" {
#endif


#ifndef EHS_VALUE
#define EHS_VALUE               20000000U
#endif

#ifndef ELS_VALUE
#define ELS_VALUE               32768U
#endif

#ifndef IHS_VALUE
#define IHS_VALUE               24000000U
#endif

#ifndef ILS_VALUE
#define ILS_VALUE               32768U
#endif

typedef enum {
    Supervisor_Software_IRQn        =  1U,
    Machine_Software_IRQn           =  3U,
    Supervisor_Timer_IRQn           =  5U,
    Machine_Timer_IRQn              =  7U,
    Supervisor_External_IRQn        =  9U,
    Machine_External_IRQn           =  11U,

    DW_GPIO0_IRQn                   =  60U,
    DW_GPIO1_IRQn                   =  61U,
    DW_GPIO2_IRQn                   =  62U,
    DW_GPIO3_IRQn                   =  63U,
    DW_RTC_GPIO_IRQn                =  70U,
    DW_UART0_IRQn                   =  44U,
    DW_UART1_IRQn                   =  45U,
    DW_UART2_IRQn                   =  46U,
    DW_UART3_IRQn                   =  47U,
    DW_UART4_IRQn                   =  48U,
    DW_IIC0_IRQn                    =  49U,
    DW_IIC1_IRQn                    =  50U,
    DW_IIC2_IRQn                    =  51U,
    DW_IIC3_IRQn                    =  52U,
    DW_IIC4_IRQn                    =  53U,
    DW_SPI0_IRQn                    =  54U,
    DW_SPI1_IRQn                    =  55U,
    DW_SPI2_IRQn                    =  56U,
    DW_SPI3_IRQn                    =  57U,
    DW_MAC_IRQn                   	=  31U,
    ADC_IRQn                        =  100U,
    SD0_INTR                        =  36U,
    SD1_INTR                        =  38U,
    SD2_INTR                        =  34U,
    WDT1_INTR                       =  58U,
#if defined(CONFIG_RISCV_SMODE) && CONFIG_RISCV_SMODE
    CORET_IRQn                      =  Supervisor_Timer_IRQn,
#else
    CORET_IRQn                      =  Machine_Timer_IRQn,
#endif	
    TEMPSEN_INTR                    =  16U,
} irqn_type_t;

typedef enum {
    CAM_MCLK0,
    CAM_PD0,
    CAM_RST0,
    CAM_MCLK1,
    CAM_PD1,
    IIC3_SCL,
    IIC3_SDA,
    SD0_CLK,
    SD0_CMD,
    SD0_D0,
    SD0_D1,
    SD0_D2,
    SD0_D3,
    SD0_CD,
    SD0_PWR_EN,
    SPK_EN,
    UART0_TX,
    UART0_RX,
    EMMC_RSTN,
    EMMC_DAT2,
    EMMC_CLK,
    EMMC_DAT0,
    EMMC_DAT3,
    EMMC_CMD,
    EMMC_DAT1,
    JTAG_CPU_TMS,
    JTAG_CPU_TCK,
    JTAG_CPU_TRST,
    IIC0_SCL,
    IIC0_SDA,
    AUX0,
    PWR_VBAT_DET,
    PWR_RSTN,
    PWR_SEQ1,
    PWR_SEQ2,
    PWR_SEQ3,
    PWR_WAKEUP0,
    PWR_WAKEUP1,
    PWR_BUTTON1,
    PWR_ON,
    XTAL_XIN,
    PWR_GPIO0,
    PWR_GPIO1,
    PWR_GPIO2,
    CLK32K,
    CLK25M,
    IIC2_SCL,
    IIC2_SDA,
    UART2_TX,
    UART2_RTS,
    UART2_RX,
    UART2_CTS,
    SD1_D3,
    SD1_D2,
    SD1_D1,
    SD1_D0,
    SD1_CMD,
    SD1_CLK,
    RSTN,
    PWM0_BUCK,
    ADC3,
    ADC2,
    ADC1,
    USB_ID,
    USB_VBUS_EN,
    USB_VBUS_DET,
    PAD_ETH_TXP,
    PAD_ETH_TXM,
    PAD_ETH_RXP,
    PAD_ETH_RXM,
    VIVO_D10,
    VIVO_D9,
    VIVO_D8,
    VIVO_D7,
    VIVO_D6,
    VIVO_D5,
    VIVO_D4,
    VIVO_D3,
    VIVO_D2,
    VIVO_D1,
    VIVO_D0,
    VIVO_CLK,
    PAD_MIPIRX5N,
    PAD_MIPIRX5P,
    PAD_MIPIRX4N,
    PAD_MIPIRX4P,
    PAD_MIPIRX3N,
    PAD_MIPIRX3P,
    PAD_MIPIRX2N,
    PAD_MIPIRX2P,
    PAD_MIPIRX1N,
    PAD_MIPIRX1P,
    PAD_MIPIRX0N,
    PAD_MIPIRX0P,
    PAD_MIPI_TXM4,
    PAD_MIPI_TXP4,
    PAD_MIPI_TXM3,
    PAD_MIPI_TXP3,
    PAD_MIPI_TXM2,
    PAD_MIPI_TXP2,
    PAD_MIPI_TXM1,
    PAD_MIPI_TXP1,
    PAD_MIPI_TXM0,
    PAD_MIPI_TXP0,
    PAD_AUD_AINL_MIC,
    PAD_AUD_AINR_MIC,
    PAD_AUD_AOUTL,
    PAD_AUD_AOUTR,
    GPIO_RTX,
    GPIO_ZQ,
    PKG_TYPE0,
    PKG_TYPE1,
    PKG_TYPE2,
    MUX_SPI1_MISO,
    MUX_SPI1_MOSI,
    MUX_SPI1_CS,
    MUX_SPI1_SCK,
    PIN_NUM,
} pin_name_t;


typedef enum {
  CAM_MCLK0__CAM_MCLK0             = 0U,
  CAM_MCLK0__AUX1                  = 2U,
  CAM_MCLK0__XGPIOA_0              = 3U,
  CAM_PD0__IIS1_MCLK               = 1U,
  CAM_PD0__XGPIOA_1                = 3U,
  CAM_PD0__CAM_HS0                 = 4U,
  CAM_RST0__XGPIOA_2               = 3U,
  CAM_RST0__CAM_VS0                = 4U,
  CAM_RST0__IIC4_SCL               = 6U,
  CAM_MCLK1__CAM_MCLK1             = 0U,
  CAM_MCLK1__AUX2                  = 2U,
  CAM_MCLK1__XGPIOA_3              = 3U,
  CAM_MCLK1__CAM_HS0               = 4U,
  CAM_PD1__IIS1_MCLK               = 1U,
  CAM_PD1__XGPIOA_4                = 3U,
  CAM_PD1__CAM_VS0                 = 4U,
  CAM_PD1__IIC4_SDA                = 6U,
  IIC3_SCL__IIC3_SCL               = 0U,
  IIC3_SCL__XGPIOA_5               = 3U,
  IIC3_SDA__IIC3_SDA               = 0U,
  IIC3_SDA__XGPIOA_6               = 3U,
  SD0_CLK__SDIO0_CLK               = 0U,
  SD0_CLK__IIC1_SDA                = 1U,
  SD0_CLK__SPI0_SCK                = 2U,
  SD0_CLK__XGPIOA_7                = 3U,
  SD0_CLK__PWM_15                  = 5U,
  SD0_CLK__EPHY_LNK_LED            = 6U,
  SD0_CLK__DBG_0                   = 7U,
  SD0_CMD__SDIO0_CMD               = 0U,
  SD0_CMD__IIC1_SCL                = 1U,
  SD0_CMD__SPI0_SDO                = 2U,
  SD0_CMD__XGPIOA_8                = 3U,
  SD0_CMD__PWM_14                  = 5U,
  SD0_CMD__EPHY_SPD_LED            = 6U,
  SD0_CMD__DBG_1                   = 7U,
  SD0_D0__SDIO0_D_0                = 0U,
  SD0_D0__CAM_MCLK1                = 1U,
  SD0_D0__SPI0_SDI                 = 2U,
  SD0_D0__XGPIOA_9                 = 3U,
  SD0_D0__UART3_TX                 = 4U,
  SD0_D0__PWM_13                   = 5U,
  SD0_D0__WG0_D0                   = 6U,
  SD0_D0__DBG_2                    = 7U,
  SD0_D1__SDIO0_D_1                = 0U,
  SD0_D1__IIC1_SDA                 = 1U,
  SD0_D1__AUX0                     = 2U,
  SD0_D1__XGPIOA_10                = 3U,
  SD0_D1__UART1_TX                 = 4U,
  SD0_D1__PWM_12                   = 5U,
  SD0_D1__WG0_D1                   = 6U,
  SD0_D1__DBG_3                    = 7U,
  SD0_D2__SDIO0_D_2                = 0U,
  SD0_D2__IIC1_SCL                 = 1U,
  SD0_D2__AUX1                     = 2U,
  SD0_D2__XGPIOA_11                = 3U,
  SD0_D2__UART1_RX                 = 4U,
  SD0_D2__PWM_11                   = 5U,
  SD0_D2__WG1_D0                   = 6U,
  SD0_D2__DBG_4                    = 7U,
  SD0_D3__SDIO0_D_3                = 0U,
  SD0_D3__CAM_MCLK0                = 1U,
  SD0_D3__SPI0_CS_X                = 2U,
  SD0_D3__XGPIOA_12                = 3U,
  SD0_D3__UART3_RX                 = 4U,
  SD0_D3__PWM_10                   = 5U,
  SD0_D3__WG1_D1                   = 6U,
  SD0_D3__DBG_5                    = 7U,
  SD0_CD__SDIO0_CD                 = 0U,
  SD0_CD__XGPIOA_13                = 3U,
  SD0_PWR_EN__SDIO0_PWR_EN         = 0U,
  SD0_PWR_EN__XGPIOA_14            = 3U,
  SPK_EN__XGPIOA_15                = 3U,
  UART0_TX__UART0_TX               = 0U,
  UART0_TX__CAM_MCLK1              = 1U,
  UART0_TX__PWM_4                  = 2U,
  UART0_TX__XGPIOA_16              = 3U,
  UART0_TX__UART1_TX               = 4U,
  UART0_TX__AUX1                   = 5U,
  UART0_TX__DBG_6                  = 7U,
  UART0_RX__UART0_RX               = 0U,
  UART0_RX__CAM_MCLK0              = 1U,
  UART0_RX__PWM_5                  = 2U,
  UART0_RX__XGPIOA_17              = 3U,
  UART0_RX__UART1_RX               = 4U,
  UART0_RX__AUX0                   = 5U,
  UART0_RX__DBG_7                  = 7U,
  EMMC_RSTN__EMMC_RSTN             = 0U,
  EMMC_RSTN__XGPIOA_21             = 3U,
  EMMC_RSTN__AUX2                  = 4U,
  EMMC_DAT2__EMMC_DAT_2            = 0U,
  EMMC_DAT2__SPINOR_HOLD_X         = 1U,
  EMMC_DAT2__SPINAND_HOLD          = 2U,
  EMMC_DAT2__XGPIOA_26             = 3U,
  EMMC_CLK__EMMC_CLK               = 0U,
  EMMC_CLK__SPINOR_SCK             = 1U,
  EMMC_CLK__SPINAND_CLK            = 2U,
  EMMC_CLK__XGPIOA_22              = 3U,
  EMMC_DAT0__EMMC_DAT_0            = 0U,
  EMMC_DAT0__SPINOR_MOSI           = 1U,
  EMMC_DAT0__SPINAND_MOSI          = 2U,
  EMMC_DAT0__XGPIOA_25             = 3U,
  EMMC_DAT3__EMMC_DAT_3            = 0U,
  EMMC_DAT3__SPINOR_WP_X           = 1U,
  EMMC_DAT3__SPINAND_WP            = 2U,
  EMMC_DAT3__XGPIOA_27             = 3U,
  EMMC_CMD__EMMC_CMD               = 0U,
  EMMC_CMD__SPINOR_MISO            = 1U,
  EMMC_CMD__SPINAND_MISO           = 2U,
  EMMC_CMD__XGPIOA_23              = 3U,
  EMMC_DAT1__EMMC_DAT_1            = 0U,
  EMMC_DAT1__SPINOR_CS_X           = 1U,
  EMMC_DAT1__SPINAND_CS            = 2U,
  EMMC_DAT1__XGPIOA_24             = 3U,
  JTAG_CPU_TMS__CV_2WTMS_CR_4WTMS  = 0U,
  JTAG_CPU_TMS__CAM_MCLK0          = 1U,
  JTAG_CPU_TMS__PWM_7              = 2U,
  JTAG_CPU_TMS__XGPIOA_19          = 3U,
  JTAG_CPU_TMS__UART1_RTS          = 4U,
  JTAG_CPU_TMS__AUX0               = 5U,
  JTAG_CPU_TMS__UART1_TX           = 6U,
  JTAG_CPU_TMS__VO_D_28            = 7U,
  JTAG_CPU_TCK__CV_2WTCK_CR_4WTCK  = 0U,
  JTAG_CPU_TCK__CAM_MCLK1          = 1U,
  JTAG_CPU_TCK__PWM_6              = 2U,
  JTAG_CPU_TCK__XGPIOA_18          = 3U,
  JTAG_CPU_TCK__UART1_CTS          = 4U,
  JTAG_CPU_TCK__AUX1               = 5U,
  JTAG_CPU_TCK__UART1_RX           = 6U,
  JTAG_CPU_TCK__VO_D_29            = 7U,
  JTAG_CPU_TRST__JTAG_CPU_TRST     = 0U,
  JTAG_CPU_TRST__XGPIOA_20         = 3U,
  JTAG_CPU_TRST__VO_D_30           = 6U,
  IIC0_SCL__CV_SCL0__CR_4WTDI      = 0U,
  IIC0_SCL__UART1_TX               = 1U,
  IIC0_SCL__UART2_TX               = 2U,
  IIC0_SCL__XGPIOA_28              = 3U,
  IIC0_SCL__WG0_D0                 = 5U,
  IIC0_SCL__DBG_10                 = 7U,
  IIC0_SDA__CV_SDA0__CR_4WTDO      = 0U,
  IIC0_SDA__UART1_RX               = 1U,
  IIC0_SDA__UART2_RX               = 2U,
  IIC0_SDA__XGPIOA_29              = 3U,
  IIC0_SDA__WG0_D1                 = 5U,
  IIC0_SDA__WG1_D0                 = 6U,
  IIC0_SDA__DBG_11                 = 7U,
  AUX0__AUX0                       = 0U,
  AUX0__XGPIOA_30                  = 3U,
  AUX0__IIS1_MCLK                  = 4U,
  AUX0__VO_D_31                    = 5U,
  AUX0__WG1_D1                     = 6U,
  AUX0__DBG_12                     = 7U,
  PWR_VBAT_DET__PWR_VBAT_DET       = 0U,
  PWR_RSTN__PWR_RSTN               = 0U,
  PWR_SEQ1__PWR_SEQ1               = 0U,
  PWR_SEQ1__PWR_GPIO_3             = 3U,
  PWR_SEQ2__PWR_SEQ2               = 0U,
  PWR_SEQ2__PWR_GPIO_4             = 3U,
  PWR_SEQ3__PWR_SEQ3               = 0U,
  PWR_SEQ3__PWR_GPIO_5             = 3U,
  PTEST__PWR_PTEST                 = 0U,
  PWR_WAKEUP0__PWR_WAKEUP0         = 0U,
  PWR_WAKEUP0__PWR_IR0             = 1U,
  PWR_WAKEUP0__PWR_UART0_TX        = 2U,
  PWR_WAKEUP0__PWR_GPIO_6          = 3U,
  PWR_WAKEUP0__UART1_TX            = 4U,
  PWR_WAKEUP0__IIC4_SCL            = 5U,
  PWR_WAKEUP0__EPHY_LNK_LED        = 6U,
  PWR_WAKEUP0__WG2_D0              = 7U,
  PWR_WAKEUP1__PWR_WAKEUP1         = 0U,
  PWR_WAKEUP1__PWR_IR1             = 1U,
  PWR_WAKEUP1__PWR_GPIO_7          = 3U,
  PWR_WAKEUP1__UART1_TX            = 4U,
  PWR_WAKEUP1__IIC4_SCL            = 5U,
  PWR_WAKEUP1__EPHY_LNK_LED        = 6U,
  PWR_WAKEUP1__WG0_D0              = 7U,
  PWR_BUTTON1__PWR_BUTTON1         = 0U,
  PWR_BUTTON1__PWR_GPIO_8          = 3U,
  PWR_BUTTON1__UART1_RX            = 4U,
  PWR_BUTTON1__IIC4_SDA            = 5U,
  PWR_BUTTON1__EPHY_SPD_LED        = 6U,
  PWR_BUTTON1__WG2_D1              = 7U,
  PWR_ON__PWR_ON                   = 0U,
  PWR_ON__PWR_GPIO_9               = 3U,
  PWR_ON__UART1_RX                 = 4U,
  PWR_ON__IIC4_SDA                 = 5U,
  PWR_ON__EPHY_SPD_LED             = 6U,
  PWR_ON__WG0_D1                   = 7U,
  XTAL_XIN__PWR_XTAL_CLKIN         = 0U,
  PWR_GPIO0__PWR_GPIO_0            = 0U,
  PWR_GPIO0__UART2_TX              = 1U,
  PWR_GPIO0__PWR_UART0_RX          = 2U,
  PWR_GPIO0__PWM_8                 = 4U,
  PWR_GPIO1__PWR_GPIO_1            = 0U,
  PWR_GPIO1__UART2_RX              = 1U,
  PWR_GPIO1__EPHY_LNK_LED          = 3U,
  PWR_GPIO1__PWM_9                 = 4U,
  PWR_GPIO1__PWR_IIC_SCL           = 5U,
  PWR_GPIO1__IIC2_SCL              = 6U,
  PWR_GPIO1__CV_4WTMS_CR_SDA0      = 7U,
  PWR_GPIO2__PWR_GPIO_2            = 0U,
  PWR_GPIO2__PWR_SECTICK           = 2U,
  PWR_GPIO2__EPHY_SPD_LED          = 3U,
  PWR_GPIO2__PWM_10                = 4U,
  PWR_GPIO2__PWR_IIC_SDA           = 5U,
  PWR_GPIO2__IIC2_SDA              = 6U,
  PWR_GPIO2__CV_4WTCK_CR_2WTCK     = 7U,
  CLK32K__CLK32K                   = 0U,
  CLK32K__AUX0                     = 1U,
  CLK32K__CV_4WTDI_CR_SCL0         = 2U,
  CLK32K__PWR_GPIO_10              = 3U,
  CLK32K__PWM_2                    = 4U,
  CLK32K__KEY_COL0                 = 5U,
  CLK32K__CAM_MCLK0                = 6U,
  CLK32K__DBG_0                    = 7U,
  CLK25M__CLK25M                   = 0U,
  CLK25M__AUX1                     = 1U,
  CLK25M__CV_4WTDO_CR_2WTMS        = 2U,
  CLK25M__PWR_GPIO_11              = 3U,
  CLK25M__PWM_3                    = 4U,
  CLK25M__KEY_COL1                 = 5U,
  CLK25M__CAM_MCLK1                = 6U,
  CLK25M__DBG_1                    = 7U,
  IIC2_SCL__IIC2_SCL               = 0U,
  IIC2_SCL__PWM_14                 = 1U,
  IIC2_SCL__PWR_GPIO_12            = 3U,
  IIC2_SCL__UART2_RX               = 4U,
  IIC2_SCL__KEY_COL2               = 7U,
  IIC2_SDA__IIC2_SDA               = 0U,
  IIC2_SDA__PWM_15                 = 1U,
  IIC2_SDA__PWR_GPIO_13            = 3U,
  IIC2_SDA__UART2_TX               = 4U,
  IIC2_SDA__IIS1_MCLK              = 5U,
  IIC2_SDA__IIS2_MCLK              = 6U,
  IIC2_SDA__KEY_COL3               = 7U,
  UART2_TX__UART2_TX               = 0U,
  UART2_TX__PWM_11                 = 1U,
  UART2_TX__PWR_UART1_TX           = 2U,
  UART2_TX__PWR_GPIO_14            = 3U,
  UART2_TX__KEY_ROW3               = 4U,
  UART2_TX__UART4_TX               = 5U,
  UART2_TX__IIS2_BCLK              = 6U,
  UART2_TX__WG2_D0                 = 7U,
  UART2_RTS__UART2_RTS             = 0U,
  UART2_RTS__PWM_8                 = 1U,
  UART2_RTS__PWR_GPIO_15           = 3U,
  UART2_RTS__KEY_ROW0              = 4U,
  UART2_RTS__UART4_RTS             = 5U,
  UART2_RTS__IIS2_DO               = 6U,
  UART2_RTS__WG1_D0                = 7U,
  UART2_RX__UART2_RX               = 0U,
  UART2_RX__PWM_10                 = 1U,
  UART2_RX__PWR_UART1_RX           = 2U,
  UART2_RX__PWR_GPIO_16            = 3U,
  UART2_RX__KEY_COL3               = 4U,
  UART2_RX__UART4_RX               = 5U,
  UART2_RX__IIS2_DI                = 6U,
  UART2_RX__WG2_D1                 = 7U,
  UART2_CTS__UART2_CTS             = 0U,
  UART2_CTS__PWM_9                 = 1U,
  UART2_CTS__PWR_GPIO_17           = 3U,
  UART2_CTS__KEY_ROW1              = 4U,
  UART2_CTS__UART4_CTS             = 5U,
  UART2_CTS__IIS2_LRCK             = 6U,
  UART2_CTS__WG1_D1                = 7U,
  SD1_D3__PWR_SD1_D3_VO32          = 0U,
  SD1_D3__SPI2_CS_X                = 1U,
  SD1_D3__IIC1_SCL                 = 2U,
  SD1_D3__PWR_GPIO_18              = 3U,
  SD1_D3__CAM_MCLK0                = 4U,
  SD1_D3__UART3_CTS                = 5U,
  SD1_D3__PWR_SPINOR1_CS_X         = 6U,
  SD1_D3__PWM_4                    = 7U,
  SD1_D2__PWR_SD1_D2_VO33          = 0U,
  SD1_D2__IIC1_SCL                 = 1U,
  SD1_D2__UART2_TX                 = 2U,
  SD1_D2__PWR_GPIO_19              = 3U,
  SD1_D2__CAM_MCLK0                = 4U,
  SD1_D2__UART3_TX                 = 5U,
  SD1_D2__PWR_SPINOR1_HOLD_X       = 6U,
  SD1_D2__PWM_5                    = 7U,
  SD1_D1__PWR_SD1_D1_VO34          = 0U,
  SD1_D1__IIC1_SDA                 = 1U,
  SD1_D1__UART2_RX                 = 2U,
  SD1_D1__PWR_GPIO_20              = 3U,
  SD1_D1__CAM_MCLK1                = 4U,
  SD1_D1__UART3_RX                 = 5U,
  SD1_D1__PWR_SPINOR1_WP_X         = 6U,
  SD1_D1__PWM_6                    = 7U,
  SD1_D0__PWR_SD1_D0_VO35          = 0U,
  SD1_D0__SPI2_SDI                 = 1U,
  SD1_D0__IIC1_SDA                 = 2U,
  SD1_D0__PWR_GPIO_21              = 3U,
  SD1_D0__CAM_MCLK1                = 4U,
  SD1_D0__UART3_RTS                = 5U,
  SD1_D0__PWR_SPINOR1_MISO         = 6U,
  SD1_D0__PWM_7                    = 7U,
  SD1_CMD__PWR_SD1_CMD_VO36        = 0U,
  SD1_CMD__SPI2_SDO                = 1U,
  SD1_CMD__IIC3_SCL                = 2U,
  SD1_CMD__PWR_GPIO_22             = 3U,
  SD1_CMD__CAM_VS0                 = 4U,
  SD1_CMD__EPHY_LNK_LED            = 5U,
  SD1_CMD__PWR_SPINOR1_MOSI        = 6U,
  SD1_CMD__PWM_8                   = 7U,
  SD1_CLK__PWR_SD1_CLK_VO37        = 0U,
  SD1_CLK__SPI2_SCK                = 1U,
  SD1_CLK__IIC3_SDA                = 2U,
  SD1_CLK__PWR_GPIO_23             = 3U,
  SD1_CLK__CAM_HS0                 = 4U,
  SD1_CLK__EPHY_SPD_LED            = 5U,
  SD1_CLK__PWR_SPINOR1_SCK         = 6U,
  SD1_CLK__PWM_9                   = 7U,
  RSTN__RSTN                       = 0U,
  PWM0_BUCK__PWM_0                 = 0U,
  PWM0_BUCK__XGPIOB_0              = 3U,
  ADC3__CAM_MCLK0                  = 1U,
  ADC3__IIC4_SCL                   = 2U,
  ADC3__XGPIOB_1                   = 3U,
  ADC3__PWM_12                     = 4U,
  ADC3__EPHY_LNK_LED               = 5U,
  ADC3__WG2_D0                     = 6U,
  ADC3__UART3_TX                   = 7U,
  ADC2__CAM_MCLK1                  = 1U,
  ADC2__IIC4_SDA                   = 2U,
  ADC2__XGPIOB_2                   = 3U,
  ADC2__PWM_13                     = 4U,
  ADC2__EPHY_SPD_LED               = 5U,
  ADC2__WG2_D1                     = 6U,
  ADC2__UART3_RX                   = 7U,
  ADC1__XGPIOB_3                   = 3U,
  ADC1__KEY_COL2                   = 4U,
  USB_ID__USB_ID                   = 0U,
  USB_ID__XGPIOB_4                 = 3U,
  USB_VBUS_EN__USB_VBUS_EN         = 0U,
  USB_VBUS_EN__XGPIOB_5            = 3U,
  PKG_TYPE0__PKG_TYPE0             = 0U,
  USB_VBUS_DET__USB_VBUS_DET       = 0U,
  USB_VBUS_DET__XGPIOB_6           = 3U,
  USB_VBUS_DET__CAM_MCLK0          = 4U,
  USB_VBUS_DET__CAM_MCLK1          = 5U,
  PKG_TYPE1__PKG_TYPE1             = 0U,
  PKG_TYPE2__PKG_TYPE2             = 0U,
  MUX_SPI1_MISO__UART3_RTS         = 1U,
  MUX_SPI1_MISO__IIC1_SDA          = 2U,
  MUX_SPI1_MISO__XGPIOB_8          = 3U,
  MUX_SPI1_MISO__PWM_9             = 4U,
  MUX_SPI1_MISO__KEY_COL1          = 5U,
  MUX_SPI1_MISO__SPI1_SDI          = 6U,
  MUX_SPI1_MISO__DBG_14            = 7U,
  MUX_SPI1_MOSI__UART3_RX          = 1U,
  MUX_SPI1_MOSI__IIC1_SCL          = 2U,
  MUX_SPI1_MOSI__XGPIOB_7          = 3U,
  MUX_SPI1_MOSI__PWM_8             = 4U,
  MUX_SPI1_MOSI__KEY_COL0          = 5U,
  MUX_SPI1_MOSI__SPI1_SDO          = 6U,
  MUX_SPI1_MOSI__DBG_13            = 7U,
  MUX_SPI1_CS__UART3_CTS           = 1U,
  MUX_SPI1_CS__CAM_MCLK0           = 2U,
  MUX_SPI1_CS__XGPIOB_10           = 3U,
  MUX_SPI1_CS__PWM_11              = 4U,
  MUX_SPI1_CS__KEY_ROW3            = 5U,
  MUX_SPI1_CS__SPI1_CS_X           = 6U,
  MUX_SPI1_CS__DBG_16              = 7U,
  MUX_SPI1_SCK__UART3_TX           = 1U,
  MUX_SPI1_SCK__CAM_MCLK1          = 2U,
  MUX_SPI1_SCK__XGPIOB_9           = 3U,
  MUX_SPI1_SCK__PWM_10             = 4U,
  MUX_SPI1_SCK__KEY_ROW2           = 5U,
  MUX_SPI1_SCK__SPI1_SCK           = 6U,
  MUX_SPI1_SCK__DBG_15             = 7U,
  PAD_ETH_TXP__UART3_RX            = 1U,
  PAD_ETH_TXP__IIC1_SCL            = 2U,
  PAD_ETH_TXP__XGPIOB_25           = 3U,
  PAD_ETH_TXP__PWM_13              = 4U,
  PAD_ETH_TXP__CAM_MCLK0           = 5U,
  PAD_ETH_TXP__SPI1_SDO            = 6U,
  PAD_ETH_TXP__IIS2_LRCK           = 7U,
  PAD_ETH_TXM__UART3_RTS           = 1U,
  PAD_ETH_TXM__IIC1_SDA            = 2U,
  PAD_ETH_TXM__XGPIOB_24           = 3U,
  PAD_ETH_TXM__PWM_12              = 4U,
  PAD_ETH_TXM__CAM_MCLK1           = 5U,
  PAD_ETH_TXM__SPI1_SDI            = 6U,
  PAD_ETH_TXM__IIS2_BCLK           = 7U,
  PAD_ETH_RXP__UART3_TX            = 1U,
  PAD_ETH_RXP__CAM_MCLK1           = 2U,
  PAD_ETH_RXP__XGPIOB_27           = 3U,
  PAD_ETH_RXP__PWM_15              = 4U,
  PAD_ETH_RXP__CAM_HS0             = 5U,
  PAD_ETH_RXP__SPI1_SCK            = 6U,
  PAD_ETH_RXP__IIS2_DO             = 7U,
  PAD_ETH_RXM__UART3_CTS           = 1U,
  PAD_ETH_RXM__CAM_MCLK0           = 2U,
  PAD_ETH_RXM__XGPIOB_26           = 3U,
  PAD_ETH_RXM__PWM_14              = 4U,
  PAD_ETH_RXM__CAM_VS0             = 5U,
  PAD_ETH_RXM__SPI1_CS_X           = 6U,
  PAD_ETH_RXM__IIS2_DI             = 7U,
  VIVO_D10__PWM_1                  = 0U,
  VIVO_D10__VI1_D_10               = 1U,
  VIVO_D10__VO_D_23                = 2U,
  VIVO_D10__XGPIOB_11              = 3U,
  VIVO_D10__RMII0_IRQ              = 4U,
  VIVO_D10__CAM_MCLK0              = 5U,
  VIVO_D10__IIC1_SDA               = 6U,
  VIVO_D10__UART2_TX               = 7U,
  VIVO_D9__PWM_2                   = 0U,
  VIVO_D9__VI1_D_9                 = 1U,
  VIVO_D9__VO_D_22                 = 2U,
  VIVO_D9__XGPIOB_12               = 3U,
  VIVO_D9__CAM_MCLK1               = 5U,
  VIVO_D9__IIC1_SCL                = 6U,
  VIVO_D9__UART2_RX                = 7U,
  VIVO_D8__PWM_3                   = 0U,
  VIVO_D8__VI1_D_8                 = 1U,
  VIVO_D8__VO_D_21                 = 2U,
  VIVO_D8__XGPIOB_13               = 3U,
  VIVO_D8__RMII0_MDIO              = 4U,
  VIVO_D8__SPI3_SDO                = 5U,
  VIVO_D8__IIC2_SCL                = 6U,
  VIVO_D8__CAM_VS0                 = 7U,
  VIVO_D7__VI2_D_7                 = 0U,
  VIVO_D7__VI1_D_7                 = 1U,
  VIVO_D7__VO_D_20                 = 2U,
  VIVO_D7__XGPIOB_14               = 3U,
  VIVO_D7__RMII0_RXD1              = 4U,
  VIVO_D7__SPI3_SDI                = 5U,
  VIVO_D7__IIC2_SDA                = 6U,
  VIVO_D7__CAM_HS0                 = 7U,
  VIVO_D6__VI2_D_6                 = 0U,
  VIVO_D6__VI1_D_6                 = 1U,
  VIVO_D6__VO_D_19                 = 2U,
  VIVO_D6__XGPIOB_15               = 3U,
  VIVO_D6__RMII0_REFCLKI           = 4U,
  VIVO_D6__SPI3_SCK                = 5U,
  VIVO_D6__UART2_TX                = 6U,
  VIVO_D6__CAM_VS0                 = 7U,
  VIVO_D5__VI2_D_5                 = 0U,
  VIVO_D5__VI1_D_5                 = 1U,
  VIVO_D5__VO_D_18                 = 2U,
  VIVO_D5__XGPIOB_16               = 3U,
  VIVO_D5__RMII0_RXD0              = 4U,
  VIVO_D5__SPI3_CS_X               = 5U,
  VIVO_D5__UART2_RX                = 6U,
  VIVO_D5__CAM_HS0                 = 7U,
  VIVO_D4__VI2_D_4                 = 0U,
  VIVO_D4__VI1_D_4                 = 1U,
  VIVO_D4__VO_D_17                 = 2U,
  VIVO_D4__XGPIOB_17               = 3U,
  VIVO_D4__RMII0_MDC               = 4U,
  VIVO_D4__IIC1_SDA                = 5U,
  VIVO_D4__UART2_CTS               = 6U,
  VIVO_D4__CAM_VS0                 = 7U,
  VIVO_D3__VI2_D_3                 = 0U,
  VIVO_D3__VI1_D_3                 = 1U,
  VIVO_D3__VO_D_16                 = 2U,
  VIVO_D3__XGPIOB_18               = 3U,
  VIVO_D3__RMII0_TXD0              = 4U,
  VIVO_D3__IIC1_SCL                = 5U,
  VIVO_D3__UART2_RTS               = 6U,
  VIVO_D3__CAM_HS0                 = 7U,
  VIVO_D2__VI2_D_2                 = 0U,
  VIVO_D2__VI1_D_2                 = 1U,
  VIVO_D2__VO_D_15                 = 2U,
  VIVO_D2__XGPIOB_19               = 3U,
  VIVO_D2__RMII0_TXD1              = 4U,
  VIVO_D2__CAM_MCLK1               = 5U,
  VIVO_D2__PWM_2                   = 6U,
  VIVO_D2__UART2_TX                = 7U,
  VIVO_D1__VI2_D_1                 = 0U,
  VIVO_D1__VI1_D_1                 = 1U,
  VIVO_D1__VO_D_14                 = 2U,
  VIVO_D1__XGPIOB_20               = 3U,
  VIVO_D1__RMII0_RXDV              = 4U,
  VIVO_D1__IIC3_SDA                = 5U,
  VIVO_D1__PWM_3                   = 6U,
  VIVO_D1__IIC4_SCL                = 7U,
  VIVO_D0__VI2_D_0                 = 0U,
  VIVO_D0__VI1_D_0                 = 1U,
  VIVO_D0__VO_D_13                 = 2U,
  VIVO_D0__XGPIOB_21               = 3U,
  VIVO_D0__RMII0_TXCLK             = 4U,
  VIVO_D0__IIC3_SCL                = 5U,
  VIVO_D0__WG1_D0                  = 6U,
  VIVO_D0__IIC4_SDA                = 7U,
  VIVO_CLK__VI2_CLK                = 0U,
  VIVO_CLK__VI1_CLK                = 1U,
  VIVO_CLK__VO_CLK1                = 2U,
  VIVO_CLK__XGPIOB_22              = 3U,
  VIVO_CLK__RMII0_TXEN             = 4U,
  VIVO_CLK__CAM_MCLK0              = 5U,
  VIVO_CLK__WG1_D1                 = 6U,
  VIVO_CLK__UART2_RX               = 7U,
  PAD_MIPIRX5N__VI1_D_11           = 1U,
  PAD_MIPIRX5N__VO_D_12            = 2U,
  PAD_MIPIRX5N__XGPIOC_0           = 3U,
  PAD_MIPIRX5N__CAM_MCLK0          = 5U,
  PAD_MIPIRX5N__WG0_D0             = 6U,
  PAD_MIPIRX5N__DBG_0              = 7U,
  PAD_MIPIRX5P__VI1_D_12           = 1U,
  PAD_MIPIRX5P__VO_D_11            = 2U,
  PAD_MIPIRX5P__XGPIOC_1           = 3U,
  PAD_MIPIRX5P__IIS1_MCLK          = 4U,
  PAD_MIPIRX5P__CAM_MCLK1          = 5U,
  PAD_MIPIRX5P__WG0_D1             = 6U,
  PAD_MIPIRX5P__DBG_1              = 7U,
  PAD_MIPIRX4N__CV_4WTDI_CR_SCL0   = 0U,
  PAD_MIPIRX4N__VI0_CLK            = 1U,
  PAD_MIPIRX4N__VI1_D_13           = 2U,
  PAD_MIPIRX4N__XGPIOC_2           = 3U,
  PAD_MIPIRX4N__IIC1_SDA           = 4U,
  PAD_MIPIRX4N__CAM_MCLK0          = 5U,
  PAD_MIPIRX4N__KEY_ROW0           = 6U,
  PAD_MIPIRX4N__MUX_SPI1_SCK       = 7U,
  PAD_MIPIRX4P__CV_4WTMS_CR_SDA0   = 0U,
  PAD_MIPIRX4P__VI0_D_0            = 1U,
  PAD_MIPIRX4P__VI1_D_14           = 2U,
  PAD_MIPIRX4P__XGPIOC_3           = 3U,
  PAD_MIPIRX4P__IIC1_SCL           = 4U,
  PAD_MIPIRX4P__CAM_MCLK1          = 5U,
  PAD_MIPIRX4P__KEY_ROW1           = 6U,
  PAD_MIPIRX4P__MUX_SPI1_CS        = 7U,
  PAD_MIPIRX3N__CV_4WTDO_CR_2WTMS  = 0U,
  PAD_MIPIRX3N__VI0_D_1            = 1U,
  PAD_MIPIRX3N__VI1_D_15           = 2U,
  PAD_MIPIRX3N__XGPIOC_4           = 3U,
  PAD_MIPIRX3N__CAM_MCLK0          = 4U,
  PAD_MIPIRX3N__MUX_SPI1_MISO      = 7U,
  PAD_MIPIRX3P__CV_4WTCK_CR_2WTCK  = 0U,
  PAD_MIPIRX3P__VI0_D_2            = 1U,
  PAD_MIPIRX3P__VI1_D_16           = 2U,
  PAD_MIPIRX3P__XGPIOC_5           = 3U,
  PAD_MIPIRX3P__MUX_SPI1_MOSI      = 7U,
  PAD_MIPIRX2N__VI0_D_3            = 1U,
  PAD_MIPIRX2N__VO_D_10            = 2U,
  PAD_MIPIRX2N__XGPIOC_6           = 3U,
  PAD_MIPIRX2N__VI1_D_17           = 4U,
  PAD_MIPIRX2N__IIC4_SCL           = 5U,
  PAD_MIPIRX2N__DBG_6              = 7U,
  PAD_MIPIRX2P__VI0_D_4            = 1U,
  PAD_MIPIRX2P__VO_D_9             = 2U,
  PAD_MIPIRX2P__XGPIOC_7           = 3U,
  PAD_MIPIRX2P__VI1_D_18           = 4U,
  PAD_MIPIRX2P__IIC4_SDA           = 5U,
  PAD_MIPIRX2P__DBG_7              = 7U,
  PAD_MIPIRX1N__VI0_D_5            = 1U,
  PAD_MIPIRX1N__VO_D_8             = 2U,
  PAD_MIPIRX1N__XGPIOC_8           = 3U,
  PAD_MIPIRX1N__KEY_ROW3           = 6U,
  PAD_MIPIRX1N__DBG_8              = 7U,
  PAD_MIPIRX1P__VI0_D_6            = 1U,
  PAD_MIPIRX1P__VO_D_7             = 2U,
  PAD_MIPIRX1P__XGPIOC_9           = 3U,
  PAD_MIPIRX1P__IIC1_SDA           = 4U,
  PAD_MIPIRX1P__KEY_ROW2           = 6U,
  PAD_MIPIRX1P__DBG_9              = 7U,
  PAD_MIPIRX0N__VI0_D_7            = 1U,
  PAD_MIPIRX0N__VO_D_6             = 2U,
  PAD_MIPIRX0N__XGPIOC_10          = 3U,
  PAD_MIPIRX0N__IIC1_SCL           = 4U,
  PAD_MIPIRX0N__CAM_MCLK1          = 5U,
  PAD_MIPIRX0N__DBG_10             = 7U,
  PAD_MIPIRX0P__VI0_D_8            = 1U,
  PAD_MIPIRX0P__VO_D_5             = 2U,
  PAD_MIPIRX0P__XGPIOC_11          = 3U,
  PAD_MIPIRX0P__CAM_MCLK0          = 4U,
  PAD_MIPIRX0P__DBG_11             = 7U,
  PAD_MIPI_TXM4__VI0_D_15          = 0U,
  PAD_MIPI_TXM4__SD1_CLK           = 1U,
  PAD_MIPI_TXM4__VO_D_24           = 2U,
  PAD_MIPI_TXM4__XGPIOC_18         = 3U,
  PAD_MIPI_TXM4__CAM_MCLK1         = 4U,
  PAD_MIPI_TXM4__PWM_12            = 5U,
  PAD_MIPI_TXM4__IIC1_SDA          = 6U,
  PAD_MIPI_TXM4__DBG_18            = 7U,
  PAD_MIPI_TXP4__VI0_D_16          = 0U,
  PAD_MIPI_TXP4__SD1_CMD           = 1U,
  PAD_MIPI_TXP4__VO_D_25           = 2U,
  PAD_MIPI_TXP4__XGPIOC_19         = 3U,
  PAD_MIPI_TXP4__CAM_MCLK0         = 4U,
  PAD_MIPI_TXP4__PWM_13            = 5U,
  PAD_MIPI_TXP4__IIC1_SCL          = 6U,
  PAD_MIPI_TXP4__DBG_19            = 7U,
  PAD_MIPI_TXM3__VI0_D_17          = 0U,
  PAD_MIPI_TXM3__SD1_D0            = 1U,
  PAD_MIPI_TXM3__VO_D_26           = 2U,
  PAD_MIPI_TXM3__XGPIOC_20         = 3U,
  PAD_MIPI_TXM3__IIC2_SDA          = 4U,
  PAD_MIPI_TXM3__PWM_14            = 5U,
  PAD_MIPI_TXM3__IIC1_SDA          = 6U,
  PAD_MIPI_TXM3__CAM_VS0           = 7U,
  PAD_MIPI_TXP3__VI0_D_18          = 0U,
  PAD_MIPI_TXP3__SD1_D1            = 1U,
  PAD_MIPI_TXP3__VO_D_27           = 2U,
  PAD_MIPI_TXP3__XGPIOC_21         = 3U,
  PAD_MIPI_TXP3__IIC2_SCL          = 4U,
  PAD_MIPI_TXP3__PWM_15            = 5U,
  PAD_MIPI_TXP3__IIC1_SCL          = 6U,
  PAD_MIPI_TXP3__CAM_HS0           = 7U,
  PAD_MIPI_TXM2__CV_4WTMS_CR_SDA0  = 0U,
  PAD_MIPI_TXM2__VI0_D_13          = 1U,
  PAD_MIPI_TXM2__VO_D_0            = 2U,
  PAD_MIPI_TXM2__XGPIOC_16         = 3U,
  PAD_MIPI_TXM2__IIC1_SDA          = 4U,
  PAD_MIPI_TXM2__PWM_8             = 5U,
  PAD_MIPI_TXM2__SPI0_SCK          = 6U,
  PAD_MIPI_TXM2__SD1_D2            = 7U,
  PAD_MIPI_TXP2__CV_4WTDI_CR_SCL0  = 0U,
  PAD_MIPI_TXP2__VI0_D_14          = 1U,
  PAD_MIPI_TXP2__VO_CLK0           = 2U,
  PAD_MIPI_TXP2__XGPIOC_17         = 3U,
  PAD_MIPI_TXP2__IIC1_SCL          = 4U,
  PAD_MIPI_TXP2__PWM_9             = 5U,
  PAD_MIPI_TXP2__SPI0_CS_X         = 6U,
  PAD_MIPI_TXP2__SD1_D3            = 7U,
  PAD_MIPI_TXM1__CV_4WTDO_CR_2WTMS = 0U,
  PAD_MIPI_TXM1__VI0_D_11          = 1U,
  PAD_MIPI_TXM1__VO_D_2            = 2U,
  PAD_MIPI_TXM1__XGPIOC_14         = 3U,
  PAD_MIPI_TXM1__IIC2_SDA          = 4U,
  PAD_MIPI_TXM1__PWM_10            = 5U,
  PAD_MIPI_TXM1__SPI0_SDO          = 6U,
  PAD_MIPI_TXM1__DBG_14            = 7U,
  PAD_MIPI_TXP1__CV_4WTCK_CR_2WTCK = 0U,
  PAD_MIPI_TXP1__VI0_D_12          = 1U,
  PAD_MIPI_TXP1__VO_D_1            = 2U,
  PAD_MIPI_TXP1__XGPIOC_15         = 3U,
  PAD_MIPI_TXP1__IIC2_SCL          = 4U,
  PAD_MIPI_TXP1__PWM_11            = 5U,
  PAD_MIPI_TXP1__SPI0_SDI          = 6U,
  PAD_MIPI_TXP1__DBG_15            = 7U,
  PAD_MIPI_TXM0__VI0_D_9           = 1U,
  PAD_MIPI_TXM0__VO_D_4            = 2U,
  PAD_MIPI_TXM0__XGPIOC_12         = 3U,
  PAD_MIPI_TXM0__CAM_MCLK1         = 4U,
  PAD_MIPI_TXM0__PWM_14            = 5U,
  PAD_MIPI_TXM0__CAM_VS0           = 6U,
  PAD_MIPI_TXM0__DBG_12            = 7U,
  PAD_MIPI_TXP0__VI0_D_10          = 1U,
  PAD_MIPI_TXP0__VO_D_3            = 2U,
  PAD_MIPI_TXP0__XGPIOC_13         = 3U,
  PAD_MIPI_TXP0__CAM_MCLK0         = 4U,
  PAD_MIPI_TXP0__PWM_15            = 5U,
  PAD_MIPI_TXP0__CAM_HS0           = 6U,
  PAD_MIPI_TXP0__DBG_13            = 7U,
  PAD_AUD_AINL_MIC__XGPIOC_23      = 3U,
  PAD_AUD_AINL_MIC__IIS1_BCLK      = 4U,
  PAD_AUD_AINL_MIC__IIS2_BCLK      = 5U,
  PAD_AUD_AINR_MIC__XGPIOC_22      = 3U,
  PAD_AUD_AINR_MIC__IIS1_DO        = 4U,
  PAD_AUD_AINR_MIC__IIS2_DI        = 5U,
  PAD_AUD_AINR_MIC__IIS1_DI        = 6U,
  PAD_AUD_AOUTL__XGPIOC_25         = 3U,
  PAD_AUD_AOUTL__IIS1_LRCK         = 4U,
  PAD_AUD_AOUTL__IIS2_LRCK         = 5U,
  PAD_AUD_AOUTR__XGPIOC_24         = 3U,
  PAD_AUD_AOUTR__IIS1_DI           = 4U,
  PAD_AUD_AOUTR__IIS2_DO           = 5U,
  PAD_AUD_AOUTR__IIS1_DO           = 6U,
  GPIO_RTX__XGPIOB_23              = 3U,
  GPIO_RTX__PWM_1                  = 4U,
  GPIO_RTX__CAM_MCLK0              = 5U,
  GPIO_ZQ__PWR_GPIO_24             = 3U,
  GPIO_ZQ__PWM_2                   = 4U,

  PIN_FUNC_GPIO                    = 3U,
  PIN_FUNC_INVALID                 = 0xff,
} pin_func_t;

typedef struct {
    pin_name_t  pin_name;
    uint8_t     idx;        ///< ctrl idx.    e.g: ADC0 channel 1, idx = 0, channel = 1
    uint8_t     channel;    ///< channel idx. e.g: same as the previous line
    pin_func_t  pin_func;
} cvi_pinmap_t;

typedef struct {
    pin_name_t pin_name;
    uint16_t cfg_reg_offset;
    uint16_t mux_reg_offset;
} pin_reg_offset_t;


typedef enum {
    CVI_OK          =  0,
    CVI_ERROR       = -1,
    CVI_BUSY        = -2,
    CVI_TIMEOUT     = -3,
    CVI_UNSUPPORTED = -4
} cvi_error_t;

typedef struct {
    unsigned long reg_base;
    uint8_t       irq_num;
    uint8_t       idx;
    void          (*irq_handler)(uint32_t irqn,void *arg);
    void           *arg;
} cvi_dev_t;

#define GET_DEV_REG_BASE(handle)     (handle->dev.reg_base)
#define GET_DEV_IDX(handle)      (handle->dev.idx)
#define GET_DEV_IRQ_NUM(handle)      (handle->dev.irq_num)
#define GET_DEV_IRQ_HANDLER(handle)  (handle->dev.irq_handler)


#define CONFIG_GPIO_NUM             2
#define CONFIG_IRQ_NUM              1023U
#define CONFIG_REAL_IRQ_CNT         105

#define PIN_MUX_BASE            0x03001000UL
#define PIN_CFG_BASE            0x03001000UL
#define PWR_PIN_CFG_BASE        0x05027000UL

#define DW_GPIO0_BASE               0x03020000UL
#define DW_GPIO1_BASE               0x03021000UL
#define DW_GPIO2_BASE               0x03022000UL
#define DW_GPIO3_BASE               0x03023000UL
#define DW_RTC_GPIO_BASE            0x05021000UL

#define CVI_WDT0_BASE                0x03010000
#define CVI_WDT1_BASE                0x03011000
#define CVI_WDT2_BASE                0x03012000
#define CVI_RTC_WDT_BASE             0x0502D000
#define CVI_WDT_SIZE                0x1000

#define CVI_TEMPSEN_BASE			0x030E0000
#define CVI_TEMPSEN_SIZE			0x10000

#define DW_UART0_BASE               0x04140000UL
#define DW_UART0_SIZE               0x1000U

#define DW_UART1_BASE               0x04150000UL
#define DW_UART1_SIZE               0x1000U

#define DW_UART2_BASE               0x04160000UL
#define DW_UART2_SIZE               0x1000U

#define DW_UART3_BASE               0x04170000UL
#define DW_UART3_SIZE               0x1000U

#define DW_UART4_BASE               0x041C0000UL
#define DW_UART4_SIZE               0x1000U

#define DW_IIC0_BASE               0x04000000UL
#define DW_IIC0_SIZE               0x1000U

#define DW_IIC1_BASE               0x04010000UL
#define DW_IIC1_SIZE               0x1000U

#define DW_IIC2_BASE               0x04020000UL
#define DW_IIC2_SIZE               0x1000U

#define DW_IIC3_BASE               0x04030000UL
#define DW_IIC3_SIZE               0x1000U

#define DW_IIC4_BASE               0x04040000UL
#define DW_IIC4_SIZE               0x1000U

#define DW_MAC_BASE                0x04070000UL
#define DW_MAC_SIZE                0x10000U

#define ADC_BASE                    0x030F0000
#define RTC_ADC_BASE                0x0502C000
#define ADC_SIZE                    0x1000

#define CVI_PWM0_BASE               0x03060000
#define CVI_PWM1_BASE               0x03061000
#define CVI_PWM2_BASE               0x03062000
#define CVI_PWM3_BASE               0x03063000

#define DW_SPI_REG_SIZE             (0x10000UL)
#define DW_SPI0_BASE                (0x04180000UL)
#define DW_SPI1_BASE                (DW_SPI0_BASE + 1 * DW_SPI_REG_SIZE)
#define DW_SPI2_BASE                (DW_SPI0_BASE + 2 * DW_SPI_REG_SIZE)
#define DW_SPI3_BASE                (DW_SPI0_BASE + 3 * DW_SPI_REG_SIZE)

#define PLIC_BASE           (0x70000000UL)
#define CORET_BASE          (PLIC_BASE + 0x4000000UL)               /*!< CORET Base Address */
#define PLIC                ((PLIC_Type *)PLIC_BASE)

#define DW_SDIO0_BASE               0x04320000  // SDIO
#define DW_SDIO1_BASE               0x04310000  // SD
#define DW_SDIO2_BASE               0x04300000  // MMC

/* ================================================================================ */
/* ================                  otp declaration               ================ */
/* ================================================================================ */
#define CONFIG_OTP_BASE_ADDR 0U
#define CONFIG_OTP_BANK_SIZE 256U    // Bytes

extern const pin_reg_offset_t cvi_pin_reg_offset[];

#ifdef __cplusplus
}
#endif

#endif  /* _SOC_H_ */