
## 第一部分： 基础信息
name: sdk_chip_phy6220                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.4.3                                     # <必选项> 组件版本号
description: chip sdk for phy6220                    # <必选项> 建议至少20字以上
type: sdk                                           # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - aos: v7.4.3
  - aos_hal: v7.4.3
  - chip_phy6220: v7.4.3
  - csi: v7.4.3
  - drv_bt_phy6220: v7.4.3
  - drivers: v7.4.3
  - hal_csi: v7.4.3
  - kv: v7.4.3
  - key_mgr: v7.4.3
  - minilibc: v7.4.3
  - phy6220_evb: v7.4.3
  - rhino: v7.4.3
  - rhino_arch_phy6220: v7.4.3
  - rhino_pwrmgmt: v7.4.3
  - partition: v7.4.3
  - sec_crypto: v7.4.3
  - uservice: v7.4.3
  - ulog: v7.4.3
