#ifndef REG_SYSC_SEC_TYPE_H_
#define REG_SYSC_SEC_TYPE_H_
#include <stdint.h>

typedef struct
{
    volatile uint32_t PD_SEC_CLKG;
    volatile uint32_t PD_SEC_SRST;
    volatile uint32_t RESERVED0[2];
    volatile uint32_t SEC_DBG;
    volatile uint32_t WKUP_CTRL;
}reg_sysc_sec_t;

enum SYSC_SEC_REG_PD_SEC_CLKG_FIELD
{
    SYSC_SEC_CLKG_SET_TRNG_MASK = (int)0x1,
    SYSC_SEC_CLKG_SET_TRNG_POS = 0,
    SYSC_SEC_CLKG_CLR_TRNG_MASK = (int)0x2,
    SYSC_SEC_CLKG_CLR_TRNG_POS = 1,
    SYSC_SEC_CLKG_SET_ECC_MASK = (int)0x4,
    SYSC_SEC_CLKG_SET_ECC_POS = 2,
    SYSC_SEC_CLKG_CLR_ECC_MASK = (int)0x8,
    SYSC_SEC_CLKG_CLR_ECC_POS = 3,
    SYSC_SEC_CLKG_SET_CALC_MASK = (int)0x10,
    SYSC_SEC_CLKG_SET_CALC_POS = 4,
    SYSC_SEC_CLKG_CLR_CALC_MASK = (int)0x20,
    SYSC_SEC_CLKG_CLR_CALC_POS = 5,
    SYSC_SEC_CLKG_SET_CRYPT_MASK = (int)0x40,
    SYSC_SEC_CLKG_SET_CRYPT_POS = 6,
    SYSC_SEC_CLKG_CLR_CRYPT_MASK = (int)0x80,
    SYSC_SEC_CLKG_CLR_CRYPT_POS = 7,
};

enum SYSC_SEC_REG_PD_SEC_SRST_FIELD
{
    SYSC_SEC_SRST_SET_TRNG_N_MASK = (int)0x1,
    SYSC_SEC_SRST_SET_TRNG_N_POS = 0,
    SYSC_SEC_SRST_CLR_TRNG_N_MASK = (int)0x2,
    SYSC_SEC_SRST_CLR_TRNG_N_POS = 1,
    SYSC_SEC_SRST_SET_ECC_N_MASK = (int)0x4,
    SYSC_SEC_SRST_SET_ECC_N_POS = 2,
    SYSC_SEC_SRST_CLR_ECC_N_MASK = (int)0x8,
    SYSC_SEC_SRST_CLR_ECC_N_POS = 3,
    SYSC_SEC_SRST_SET_CALC_N_MASK = (int)0x10,
    SYSC_SEC_SRST_SET_CALC_N_POS = 4,
    SYSC_SEC_SRST_CLR_CALC_N_MASK = (int)0x20,
    SYSC_SEC_SRST_CLR_CALC_N_POS = 5,
    SYSC_SEC_SRST_SET_CRYPT_N_MASK = (int)0x40,
    SYSC_SEC_SRST_SET_CRYPT_N_POS = 6,
    SYSC_SEC_SRST_CLR_CRYPT_N_MASK = (int)0x80,
    SYSC_SEC_SRST_CLR_CRYPT_N_POS = 7,
};

enum SYSC_SEC_REG_SEC_DBG_FIELD
{
    SYSC_SEC_SYSC_SEC_DBG_MASK = (int)0xff,
    SYSC_SEC_SYSC_SEC_DBG_POS = 0,
};

enum SYSC_SEC_REG_WKUP_CTRL_FIELD
{
    SYSC_SEC_PDSEC_WKUP_MSK_MASK = (int)0x7,
    SYSC_SEC_PDSEC_WKUP_MSK_POS = 0,
};

#endif

