Import("env")
src = [
    'lsqspi_msp.c',
    'uart_msp.c',
    'platform.c',
    'cpu.c',
    'modem_rf_sagi.c',
    'io_config.c',
    'delay_asm.S',
    'sleep_asm.S',
    'sleep.c',
    'int_call_asm.S',
]
inc = [
    '.',
]
start_src = [
    'startup_asm.S',
    'startup.c',
]
src_files = File(src)
inc_dirs = Dir(inc)
start_files = File(start_src)
env['LINKSCRIPT'] = File("link_script.txt")
Return("src_files","inc_dirs","start_files")