
## 第一部分： 基础信息
name: amrnb                                         # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
description: amrnb                                  # <必选项> 建议至少20字以上
type: common                                        # <可选项> 组件类型，为：solution, chip, board, common，缺省值 common

tag: 多媒体播放器                                   # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - amrnb
  - audio decoder & encoder
  - media
yoc_version: ['v7.2', 'v7.3']
author:                                             # <可选项> 原作者信息
  name: jingzhishen
  email: jingzhishen@126.com
license: APACHE                                     # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - csi: V7.2.2
  - rhino: V7.2.2
  - minilibc: V7.2.2
  - aos: V7.2.2

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cxxflag: ' -Wall -O2 -Wno-attributes '
  define:
    - WMOPS=0
  include:
    - include
  internal_include:
    - src
    - src/common/include
    - src/dec/src
    - include/amrnb

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "src/dec/src/amrdecode.cpp"
  - "src/dec/src/a_refl.cpp"
  - "src/dec/src/wmf_to_ets.cpp"
  - "src/dec/src/d2_11pf.cpp"
  - "src/dec/src/d_plsf.cpp"
  - "src/dec/src/c_g_aver.cpp"
  - "src/dec/src/d4_17pf.cpp"
  - "src/dec/src/dec_amr.cpp"
  - "src/dec/src/ec_gains.cpp"
  - "src/dec/src/pstfilt.cpp"
  - "src/dec/src/d2_9pf.cpp"
  - "src/dec/src/if2_to_ets.cpp"
  - "src/dec/src/agc.cpp"
  - "src/dec/src/int_lsf.cpp"
  - "src/dec/src/ex_ctrl.cpp"
  - "src/dec/src/post_pro.cpp"
  - "src/dec/src/lsp_avg.cpp"
  - "src/dec/src/d3_14pf.cpp"
  - "src/dec/src/bgnscd.cpp"
  - "src/dec/src/dec_lag6.cpp"
  - "src/dec/src/dec_lag3.cpp"
  - "src/dec/src/d_plsf_3.cpp"
  - "src/dec/src/dec_gain.cpp"
  - "src/dec/src/d_plsf_5.cpp"
  - "src/dec/src/d_gain_c.cpp"
  - "src/dec/src/d1035pf.cpp"
  - "src/dec/src/d8_31pf.cpp"
  - "src/dec/src/sp_dec.cpp"
  - "src/dec/src/dec_input_format_tab.cpp"
  - "src/dec/src/b_cn_cod.cpp"
  - "src/dec/src/preemph.cpp"
  - "src/dec/src/qgain475_tab.cpp"
  - "src/dec/src/d_gain_p.cpp"
  - "src/dec/src/dtx_dec.cpp"
  - "src/dec/src/ph_disp.cpp"
  - "src/common/src/l_shr_r.cpp"
  - "src/common/src/l_abs.cpp"
  - "src/common/src/div_s.cpp"
  - "src/common/src/negate.cpp"
  - "src/common/src/mult_r.cpp"
  - "src/common/src/grid_tbl.cpp"
  - "src/common/src/copy.cpp"
  - "src/common/src/ph_disp_tab.cpp"
  - "src/common/src/q_plsf_3.cpp"
  - "src/common/src/lsp_tab.cpp"
  - "src/common/src/int_lpc.cpp"
  - "src/common/src/sub.cpp"
  - "src/common/src/lsp_lsf_tbl.cpp"
  - "src/common/src/vad1.cpp"
  - "src/common/src/round.cpp"
  - "src/common/src/log2_norm.cpp"
  - "src/common/src/inv_sqrt_tbl.cpp"
  - "src/common/src/log2_tbl.cpp"
  - "src/common/src/syn_filt.cpp"
  - "src/common/src/q_plsf_5.cpp"
  - "src/common/src/add.cpp"
  - "src/common/src/gray_tbl.cpp"
  - "src/common/src/norm_s.cpp"
  - "src/common/src/az_lsp.cpp"
  - "src/common/src/inv_sqrt.cpp"
  - "src/common/src/gmed_n.cpp"
  - "src/common/src/lsfwt.cpp"
  - "src/common/src/sqrt_l_tbl.cpp"
  - "src/common/src/log2.cpp"
  - "src/common/src/q_plsf_3_tbl.cpp"
  - "src/common/src/q_plsf_5_tbl.cpp"
  - "src/common/src/bitreorder_tab.cpp"
  - "src/common/src/gains_tbl.cpp"
  - "src/common/src/shr_r.cpp"
  - "src/common/src/l_deposit_l.cpp"
  - "src/common/src/window_tab.cpp"
  - "src/common/src/norm_l.cpp"
  - "src/common/src/lsp_az.cpp"
  - "src/common/src/weight_a.cpp"
  - "src/common/src/pow2_tbl.cpp"
  - "src/common/src/extract_l.cpp"
  - "src/common/src/reorder.cpp"
  - "src/common/src/pred_lt.cpp"
  - "src/common/src/sqrt_l.cpp"
  - "src/common/src/pow2.cpp"
  - "src/common/src/q_plsf.cpp"
  - "src/common/src/gc_pred.cpp"
  - "src/common/src/div_32.cpp"
  - "src/common/src/lsp_lsf.cpp"
  - "src/common/src/residu.cpp"
  - "src/common/src/lsp.cpp"
  - "src/common/src/qua_gain_tbl.cpp"
  - "src/common/src/bitno_tab.cpp"
  - "src/common/src/bits2prm.cpp"
  - "src/common/src/extract_h.cpp"
  - "src/common/src/set_zero.cpp"
  - "src/common/src/c2_9pf_tab.cpp"
  - "src/common/src/shr.cpp"
  - "src/common/src/l_deposit_h.cpp"

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/"
    source:
      - "include/*"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
