
## 第一部分： 基础信息
name: chip_d1                                    # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.0                                   # <必选项> 组件版本号
description: driver & sdk for platform/mcu d1  chip         # <必选项> 建议至少20字以上
type: chip                                          # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：">= v1.0",
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.y
#   - sdk_chip_riscv_dummy: v7.4.y
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: v7.2.0

## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: t-head
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb             # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀

## chip component (单处理器)
# hw_info:
#   cpu_name: CK804EF
#   ld_script: configs/gcc_eflash.ld
#   toolchain_prefix: csky-abiv2-elf
#   flash_program: bin/flash_program.elf

## chip component(多处理器)
# hw_info:
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
hw_info:
  arch_name: riscv
  cpu_name: c906fdv
  toolchain_prefix: riscv64-unknown-elf
  vendor_name: allwinner
  ld_script: gcc_flash.ld
  flash_program: d1_flash.elf

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag:
  cxxflag:
  ldflag:
  asmflag: -D__ASSEMBLY__
  libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
    - chip_d1_melis                      #   -lxxx
  libpath:                               # 指定静态库所在的路径（相对于该组件路径）
    - libs/<CONFIG_MELIS_LIB_SUB_PATH>   #   -Llibs
  include:
    - include
    - include/asm
    - pcm/include
    - melis/include/hal/sdmmc
    - melis/include/hal/sdmmc/osal
  # internal_include:
  #   - melis/include/osal
  #   - melis/include/hal
  #   - melis/misc/video
  #   - melis/misc/
  #   - melis/hal/source
  #   - melis/hal/source/gpio
  #   - melis/hal/source/mbus
  #   - melis/hal/source/regulator
  #   - melis/hal/source/ccmu/sunxi-ng
  #   - melis/hal/source/ccmu/
  #   - melis/hal/source/rtc
  #   - melis/hal/source/gpadc
  #   - melis/hal/source/lradc
  #   - melis/hal/source/dma
  #   - melis/hal/source/pwm
  #   - melis
  #   - melis/hal/source/disp2/disp
  #   - melis/hal/source/disp2/disp/de
  #   - melis/hal/source/disp2/disp/de/lowlevel_v2x
  #   - melis/hal/source/disp2/disp/lcd
  #   - melis/hal/source/disp2/soc
  #   - melis/hal/source/g2d_rcq
  #   - sys/d1
  #   - sys
  #   - drivers/ll
  #   - melis/hal/source/sound/platform/
  #   - melis/hal/source/sound/codecs/
  #   - melis/hal/source/sound/component/aw-alsa-utils/
  #   # sdmmmc
  #   - melis/include/hal/sdmmc/hal
  #   - melis/include/hal/sdmmc/sys
  #   # - melis/include/hal/sdmmc/os
  #   - melis/include/hal/sdmmc/osal/aos

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_PLIC_BASE: 0x10000000
  CONFIG_MELIS_LIB_SUB_PATH: "/"
  CONFIG_VIC_TSPDR: 0x14000000
  CONFIG_LOG_DEFAULT_LEVEL: 2
  HAVE_INIT_ARRAY_LD: y
  CONFIG_NON_ADDRESS_FLASH: y
  CONFIG_CSI_V2: 1
  CONFIG_CSI: "csi2"
  CONFIG_CPU_C906FDV: 1
  CONFIG_RISCV_VECTOR_LEN: 128
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_SOC_SUN20I: 1
  CONFIG_SOC_SUN20IW1: 1
  CONFIG_SOC_SUN20IW1P1: 1
  CONFIG_ARCH_SUN20IW1: 1
  CONFIG_DRIVERS_SUNXI_CCU: 1   # common_ccmu.h
  CONFIG_SHM_ALIGN_CACHE: 64
  CONFIG_USE_MINIALSA: 1
  # SPINOR
  CONFIG_SUNXI_SPI_CPU_XFER_ONLY: 1 # SPI not DMA
  CONFIG_DRIVERS_SPINOR_FREQ: 50
  CONFIG_DRIVERS_SPINOR_4K_SECTORS: 1
  #
  # CONFIG_U_FLASH_CORE: 1

  # MTD partition config to support mtd vfs apis(open/close/read/write/ioctl).
  # MTD_PART_ID_FS:        0
  # MTD_PART_ID_KV:        1
  # SOUND
  CONFIG_DRIVERS_DMA: 1
  CONFIG_DRIVERS_SOUND: 1
  CONFIG_SND_CODEC_SUN8IW20_AUDIOCODEC: 1
  CONFIG_SND_PLATFORM_SUNXI_PCM: 1
  CONFIG_SND_PLATFORM_SUNXI_CPUDAI: 1
  CONFIG_SND_PLATFORM_SUNXI_DAUDIO: 1
  # CONFIG_SND_PLATFORM_SUNXI_DAUDIO0: 1
  CONFIG_BUILTIN_WAV_FILE: 1
  CONFIG_SND_PLATFORM_SUNXI_DMIC: 1
  # DISPLAY
  CONFIG_LCD_SUPPORT_TFT08006: 1
  CONFIG_LCD_SUPPORT_RE_TFT720P: 1
  MIPI_DSI_IP_VERSION: 40
  CONFIG_DISP2_SUNXI_SUPPORT_ENAHNCE: 1
  CONFIG_SUNXI_DISP2_FB_DISABLE_ROTATE: 1
  # TOUCH
  CONFIG_DRIVERS_TOUCH: 1
  #wifi x829
  CONFIG_BACKEND_XRADIO: 1
  CONFIG_DRIVER_XRADIO: 1
  CONFIG_CRYPTO_INTERNAL: 1
  CONFIG_NO_RANDOM_POOL: 1
  CONFIG_NO_CONFIG_BLOBS: 1
  CONFIG_NO_ROAMING: 1
  CONFIG_NO_RADIUS: 1
  CONFIG_NO_ACCOUNTING: 1
  CONFIG_NO_VLAN: 1
  CONFIG_NO_CTRL_IFACE: 1
  CONFIG_OS_NUTTX: 1
  CONFIG_OS_NUTTX_CM_PASS: 1
  CONFIG_AOS: 1
  CONFIG_USE_SDIO: 1
  CONFIG_DETECT_CARD: 1
  CONFIG_USE_SD: 1
  CONFIG_SDIO_IRQ_SUPPORT: 1
  CONFIG_HAL_ADC_DISABLED: 1
  CONFIG_PWM_MAX_CHANNEL_COUNT: 8
## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径


## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
