## 第一部分： 基础信息
name: pangu_cpu0_evb
version: v7.4.3
description: YunVoice CPU0 board configure.
type: board
tag: 核心模块
## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - chip_pangu: v7.4.3
## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: xuantie
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb                 # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
## solution component
# hw_info:
#   cpu_id: cpu0
#   board_name: pangu_cpu0_evb
#   cpu_name: CK805EF
#   vendor_name: xuantie
#   chip_name: 'chip_pangu'
#   ld_script: configs/gcc_eflash.ld.S
## board component
# hw_info:
#   chip_name: chip_pangu
#   ld_script: configs/gcc_eflash.ld
## chip component (单处理器)
# hw_info:
#   cpu_name: CK804EF
#   ld_script: configs/gcc_eflash.ld
#   flash_program: bin/flash_program.elf
## chip component(多处理器)
# hw_info:
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
hw_info:
  cpu_id: cpu0
  cpu_name: ""
  vendor_name: ""
  chip_name: chip_pangu
  board_name: ""
  ld_script: configs/gcc_eflash.ld
  flash_program: ""
## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  include:
    - include
  internal_include: ~
  cflag: "-nostdlib -mistack -Wpointer-arith -Wundef -Wall -Wl,-EL -ffunction-sections -fdata-sections -fno-inline-functions -fno-builtin -fno-strict-aliasing -fno-strength-reduce -mhard-float\n"
  cxxflag: "-mhard-float\n"
  asmflag: "-mhard-float\n"
  define: ~
  libs: ~
  libpath: ~
  ldflag: -Wl,-zmax-page-size=1024 -mhard-float
# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - src/*.c
  - src/pwr/board_cpu_pwr.c  ? <CONFIG_KERNEL_RHINO>
  - src/pwr/board_cpu_pwr_systick.c  ? <CONFIG_KERNEL_RHINO>
  - src/pwr/board_cpu_pwr_timer.c  ? <CONFIG_KERNEL_RHINO>
## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_ARCH_CSKY: 1
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_CHIP_PANGU: 1
  CONFIG_CHIP_PANGU_CPU0: 1
  CONFIG_CPU: ck804ef
  CONFIG_CSKY_CORETIM: 1
  CONFIG_FOTA_BUFFER_SIZE: 4096
  CONFIG_HAVE_VIC: 1
  CONFIG_KERNEL_WORKQUEUE: 1
  CONFIG_SYSTICK_HZ: 100
  #CONFIG_KERNEL_SYS_STATS: 0
  #CONFIG_KERNEL_LWIP_HOOK: 0
  CONFIG_TEE_CA: 1
  CONFIG_VENDOR_NAME: xuantie
  MBEDTLS_AES_ALT: 1
  MBEDTLS_RSA_ALT: 1
  # MBEDTLS_SHA256_ALT: 1
  MBEDTLS_SHA1_ALT: 1
  STDIO_UART: 1
# CONFIG_SYSTEM_SECURE: 1
# CONFIG_CPU_CK804EF: 1
##secure config##
# CONFIG_SYSTEM_SECURE: 1
#mbedtls
#sec_crypto
#CONFIG_SEC_CRYPTO_AES_SW: 1
#CONFIG_SEC_CRYPTO_SHA_SW: 1
#CONFIG_SEC_CRYPTO_RSA_SW: 1
#CONFIG_SEC_CRYPTO_RNG_SW: 1
#CONFIG_SEC_CRYPTO_ECC_SW: 1
# FOTA config
## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: include
    source:
      - include/*.h
  - dest: pangu_cpu0_evb/bootimgs
    source:
      - bootimgs/*
  - dest: pangu_cpu0_evb/configs
    source:
      - configs/*
## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
export:
  - dest: <SOLUTION_PATH>/generated/data
    source:
      - bootimgs/boot
      - bootimgs/boot-notee
      - bootimgs/tee
      - bootimgs/cpu1
      - bootimgs/cpu2
      - bootimgs/lpm
      - bootimgs/kp
      - configs/config.yaml
keywords: ~
author:
  name: ""
license: ""
homepage: ~
# - "configs2/config.yaml"
