
## 第一部分： 基础信息
name: sdk_chip_cv181xh_bga                          # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.8.0                                    # <必选项> 组件版本号
description: the sdk chip for cv1810x               # <必选项> 建议至少20字以上
type: sdk                                           # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - yoc_kernel: v7.8.0
  - libc_stub: v7.8.0
  - posix: v7.8.0
  - vfs: v7.8.0
  - littlefs: v7.8.0
  - lwext4: v7.8.0
  - netmgr: v7.8.0
  - cjson: v7.8.0
  - mpegts: v7.8.0
  - at: v7.8.0
  - cv181xh_huashanpi_evb: v7.8.0
  - chip_cv181x: v7.8.0
  - g711: v7.8.0
  - ntp: v7.8.0
  - drv_wifi_rtl8723ds: v7.8.0
  - drv_bt_rtl8723ds: v7.8.0
  - ble_host: v7.8.0
  - lwip: v7.8.0
  - mbedtls: v7.8.0
  - minialsa: v7.8.0
  - drv_snd_cv181x: v7.8.0
  - drv_sdmmc: v7.8.0
  - fatfs: v7.8.0
  - cvi_mmf_sdk_cv181xx: v7.8.0
  - cvi_platform: v7.8.0
  - cvi_sensor: v7.8.0
  - cherryusb: v7.8.0
  - key_mgr: v7.8.0
  - sec_crypto: v7.8.0
  - bootab: v7.8.0
  - drv_touchscreen_gsl1680: v7.8.0
  - drv_display_st7701s: v7.8.0
  - drv_usbh_class: v7.8.0
