#ifndef INC_UNI_NLU_CONTENT_H_
#define INC_UNI_NLU_CONTENT_H_

typedef struct {
  unsigned int key_word_hash_code; /* 存放识别词汇对应的hashcode */
  unsigned char  nlu_content_str_index; /* 存放nlu映射表中的索引，实现多个识别词汇可对应同一个nlu，暂支持256条，如果不够换u16 */
  char    *hash_collision_orginal_str /* 类似Java String equal，当hash发生碰撞时，赋值为识别词汇，否则设置为NULL */;
} uni_nlu_content_mapping_t;

enum {
  eCMD_exitUni,
  eCMD_light_on,
  eCMD_light_off,
  eCMD_light_0_on,
  eCMD_light_0_off,
  eCMD_light_1_on,
  eCMD_light_1_off,
  eCMD_curtain_open,
  eCMD_curtain_close,
  eCMD_mode_out,
  eCMD_mode_sleep,
  eCMD_mode_movie,
  eCMD_mode_home,
  eCMD_music_vol_up,
  eCMD_music_vol_dw,
  eCMD_music_mute,
  eCMD_music_unmute,
  eCMD_music_play,
  eCMD_music_pause,
  eCMD_music_resume,
  eCMD_music_pre,
  eCMD_music_next,
  eCMD_light_b_dw,
  eCMD_light_b_up,
  eCMD_light_b_min,
  eCMD_light_b_max,
  eCMD_light_ct_up,
  eCMD_light_ct_max,
  eCMD_light_ct_dw,
  eCMD_light_ct_min,
  eCMD_ac_on,
  eCMD_ac_off,
  eCMD_ac_t_up,
  eCMD_ac_t_dw,
  eCMD_ac_w_up,
  eCMD_ac_w_dw,
  eCMD_ac_w_max,
  eCMD_ac_t_middle,
  eCMD_ac_t_min,
  eCMD_ac_m_cold,
  eCMD_ac_m_hot,
  eCMD_ac_m_auto,
  eCMD_fan_on,
  eCMD_fan_off,
  eCMD_fan_w_up,
  eCMD_fan_w_dw,
  eCMD_fan_s_on,
  eCMD_fan_s_off,
  eCMD_gauze_open,
  eCMD_gauze_close,
};

const char* const g_nlu_content_str[] = {
[eCMD_exitUni] = "{\"asrresult\":\"退下\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"exitUni\"}]}",
[eCMD_light_on] = "{\"asrresult\":\"打开照明\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_on\"}]}",
[eCMD_light_off] = "{\"asrresult\":\"关闭照明\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_off\"}]}",
[eCMD_light_0_on] = "{\"asrresult\":\"打开客厅灯\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_0_on\"}]}",
[eCMD_light_0_off] = "{\"asrresult\":\"关闭客厅灯\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_0_off\"}]}",
[eCMD_light_1_on] = "{\"asrresult\":\"打开卧室灯\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_1_on\"}]}",
[eCMD_light_1_off] = "{\"asrresult\":\"关闭卧室灯\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_1_off\"}]}",
[eCMD_curtain_open] = "{\"asrresult\":\"开窗帘\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"curtain_open\"}]}",
[eCMD_curtain_close] = "{\"asrresult\":\"关窗帘\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"curtain_close\"}]}",
[eCMD_mode_out] = "{\"asrresult\":\"离家模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"mode_out\"}]}",
[eCMD_mode_sleep] = "{\"asrresult\":\"睡眠模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"mode_sleep\"}]}",
[eCMD_mode_movie] = "{\"asrresult\":\"影音模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"mode_movie\"}]}",
[eCMD_mode_home] = "{\"asrresult\":\"回家模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"mode_home\"}]}",
[eCMD_music_vol_up] = "{\"asrresult\":\"增加音量\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_vol_up\"}]}",
[eCMD_music_vol_dw] = "{\"asrresult\":\"降低音量\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_vol_dw\"}]}",
[eCMD_music_mute] = "{\"asrresult\":\"静音\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_mute\"}]}",
[eCMD_music_unmute] = "{\"asrresult\":\"取消静音\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_unmute\"}]}",
[eCMD_music_play] = "{\"asrresult\":\"我要听歌\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_play\"}]}",
[eCMD_music_pause] = "{\"asrresult\":\"暂停播放\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_pause\"}]}",
[eCMD_music_resume] = "{\"asrresult\":\"继续播放\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_resume\"}]}",
[eCMD_music_pre] = "{\"asrresult\":\"上一首\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_pre\"}]}",
[eCMD_music_next] = "{\"asrresult\":\"下一首\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"music_next\"}]}",
[eCMD_light_b_dw] = "{\"asrresult\":\"亮度调低\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_b_dw\"}]}",
[eCMD_light_b_up] = "{\"asrresult\":\"亮度调高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_b_up\"}]}",
[eCMD_light_b_min] = "{\"asrresult\":\"亮度调到最低\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_b_min\"}]}",
[eCMD_light_b_max] = "{\"asrresult\":\"亮度调到最高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_b_max\"}]}",
[eCMD_light_ct_up] = "{\"asrresult\":\"色温调高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_ct_up\"}]}",
[eCMD_light_ct_max] = "{\"asrresult\":\"色温最高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_ct_max\"}]}",
[eCMD_light_ct_dw] = "{\"asrresult\":\"色温调低\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_ct_dw\"}]}",
[eCMD_light_ct_min] = "{\"asrresult\":\"色温最低\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"light_ct_min\"}]}",
[eCMD_ac_on] = "{\"asrresult\":\"打开空调\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_on\"}]}",
[eCMD_ac_off] = "{\"asrresult\":\"关闭空调\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_off\"}]}",
[eCMD_ac_t_up] = "{\"asrresult\":\"调高一度\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_t_up\"}]}",
[eCMD_ac_t_dw] = "{\"asrresult\":\"调低一度\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_t_dw\"}]}",
[eCMD_ac_w_up] = "{\"asrresult\":\"空调风速调高一点\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_w_up\"}]}",
[eCMD_ac_w_dw] = "{\"asrresult\":\"空调风速调低一点\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_w_dw\"}]}",
[eCMD_ac_w_max] = "{\"asrresult\":\"空调风速调到最高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_w_max\"}]}",
[eCMD_ac_t_middle] = "{\"asrresult\":\"空调风速调到中风\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_t_middle\"}]}",
[eCMD_ac_t_min] = "{\"asrresult\":\"空调风速调到微风\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_t_min\"}]}",
[eCMD_ac_m_cold] = "{\"asrresult\":\"制冷模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_m_cold\"}]}",
[eCMD_ac_m_hot] = "{\"asrresult\":\"制热模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_m_hot\"}]}",
[eCMD_ac_m_auto] = "{\"asrresult\":\"自动模式\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"ac_m_auto\"}]}",
[eCMD_fan_on] = "{\"asrresult\":\"打开风扇\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_on\"}]}",
[eCMD_fan_off] = "{\"asrresult\":\"关闭风扇\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_off\"}]}",
[eCMD_fan_w_up] = "{\"asrresult\":\"将风扇调高\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_w_up\"}]}",
[eCMD_fan_w_dw] = "{\"asrresult\":\"风量调低\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_w_dw\"}]}",
[eCMD_fan_s_on] = "{\"asrresult\":\"风扇摇头\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_s_on\"}]}",
[eCMD_fan_s_off] = "{\"asrresult\":\"停止摇头\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"fan_s_off\"}]}",
[eCMD_gauze_open] = "{\"asrresult\":\"打开纱帘\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"gauze_open\"}]}",
[eCMD_gauze_close] = "{\"asrresult\":\"关闭纱帘\",\"semantics\":[{\"domain\":\"acc\", \"intent\":\"gauze_close\"}]}",
};

/*TODO perf sort by hashcode O(logN), now version O(N)*/
const uni_nlu_content_mapping_t g_nlu_content_mapping[] = {
  {2497873774U/*退下*/, eCMD_exitUni, NULL},
  {2389288886U/*再见*/, eCMD_exitUni, NULL},
  {3450674028U/*打开照明*/, eCMD_light_on, NULL},
  {3282931849U/*打开照明灯*/, eCMD_light_on, NULL},
  {3196940412U/*打开灯*/, eCMD_light_on, NULL},
  {3269676220U/*请开灯*/, eCMD_light_on, NULL},
  {2438769644U/*开灯*/, eCMD_light_on, NULL},
  {3093277224U/*把灯打开*/, eCMD_light_on, NULL},
  {2509601055U/*关闭照明*/, eCMD_light_off, NULL},
  {1029534198U/*关闭照明灯*/, eCMD_light_off, NULL},
  {2389495330U/*关灯*/, eCMD_light_off, NULL},
  {3220401906U/*请关灯*/, eCMD_light_off, NULL},
  {631442226U/*关上灯*/, eCMD_light_off, NULL},
  {862969593U/*打开客厅灯*/, eCMD_light_0_on, NULL},
  {2741028457U/*开客厅灯*/, eCMD_light_0_on, NULL},
  {2904539238U/*关闭客厅灯*/, eCMD_light_0_off, NULL},
  {1356851231U/*关客厅灯*/, eCMD_light_0_off, NULL},
  {3652797984U/*打开卧室灯*/, eCMD_light_1_on, NULL},
  {1235889552U/*开卧室灯*/, eCMD_light_1_on, NULL},
  {1399400333U/*关闭卧室灯*/, eCMD_light_1_off, NULL},
  {4146679622U/*关卧室灯*/, eCMD_light_1_off, NULL},
  {4052027866U/*开窗帘*/, eCMD_curtain_open, NULL},
  {3484367690U/*打开窗帘*/, eCMD_curtain_open, NULL},
  {617480218U/*请打开窗帘*/, eCMD_curtain_open, NULL},
  {704787428U/*关窗帘*/, eCMD_curtain_close, NULL},
  {2543294717U/*关闭窗帘*/, eCMD_curtain_close, NULL},
  {3971374541U/*请关闭窗帘*/, eCMD_curtain_close, NULL},
  {1496735082U/*离家模式*/, eCMD_mode_out, NULL},
  {664475715U/*打开离家模式*/, eCMD_mode_out, NULL},
  {2917924970U/*设置离家模式*/, eCMD_mode_out, NULL},
  {2627810873U/*睡眠模式*/, eCMD_mode_sleep, NULL},
  {1795551506U/*打开睡眠模式*/, eCMD_mode_sleep, NULL},
  {4049000761U/*设置睡眠模式*/, eCMD_mode_sleep, NULL},
  {1492864401U/*睡觉了*/, eCMD_mode_sleep, NULL},
  {3148750845U/*影音模式*/, eCMD_mode_movie, NULL},
  {2316491478U/*打开影音模式*/, eCMD_mode_movie, NULL},
  {274973437U/*设置影音模式*/, eCMD_mode_movie, NULL},
  {934122462U/*回家模式*/, eCMD_mode_home, NULL},
  {101863095U/*打开回家模式*/, eCMD_mode_home, NULL},
  {2355312350U/*设置回家模式*/, eCMD_mode_home, NULL},
  {656604622U/*增加音量*/, eCMD_music_vol_up, NULL},
  {646640175U/*音量调高*/, eCMD_music_vol_up, NULL},
  {912662092U/*降低音量*/, eCMD_music_vol_dw, NULL},
  {646635918U/*音量调低*/, eCMD_music_vol_dw, NULL},
  {2525404728U/*静音*/, eCMD_music_mute, NULL},
  {4044933668U/*取消静音*/, eCMD_music_unmute, NULL},
  {1371721016U/*我要听歌*/, eCMD_music_play, NULL},
  {41366855U/*播放歌曲*/, eCMD_music_play, NULL},
  {1122259316U/*播放一首歌曲*/, eCMD_music_play, NULL},
  {1330294209U/*暂停播放*/, eCMD_music_pause, NULL},
  {199995221U/*继续播放*/, eCMD_music_resume, NULL},
  {3394670435U/*上一首*/, eCMD_music_pre, NULL},
  {3503572884U/*播放上一首*/, eCMD_music_pre, NULL},
  {4282174116U/*下一首*/, eCMD_music_next, NULL},
  {96109269U/*播放下一首*/, eCMD_music_next, NULL},
  {272356019U/*亮度调低*/, eCMD_light_b_dw, NULL},
  {3455764346U/*调暗一点*/, eCMD_light_b_dw, NULL},
  {1827389952U/*灯暗一点*/, eCMD_light_b_dw, NULL},
  {272360276U/*亮度调高*/, eCMD_light_b_up, NULL},
  {1648810031U/*调亮一点*/, eCMD_light_b_up, NULL},
  {175714954U/*亮一点*/, eCMD_light_b_up, NULL},
  {20435637U/*灯亮一点*/, eCMD_light_b_up, NULL},
  {1008358454U/*亮度调到最低*/, eCMD_light_b_min, NULL},
  {3928339563U/*灯亮度调到最低*/, eCMD_light_b_min, NULL},
  {160236608U/*灯调到最暗*/, eCMD_light_b_min, NULL},
  {1008362711U/*亮度调到最高*/, eCMD_light_b_max, NULL},
  {3928343820U/*灯亮度调到最高*/, eCMD_light_b_max, NULL},
  {160235701U/*灯调到最亮*/, eCMD_light_b_max, NULL},
  {3818311009U/*色温调高*/, eCMD_light_ct_up, NULL},
  {1962633659U/*灯光调暖*/, eCMD_light_ct_up, NULL},
  {939885094U/*灯暖一些*/, eCMD_light_ct_up, NULL},
  {939886271U/*灯暖一点*/, eCMD_light_ct_up, NULL},
  {3742492914U/*色温最高*/, eCMD_light_ct_max, NULL},
  {2465520126U/*白光*/, eCMD_light_ct_max, NULL},
  {3818306752U/*色温调低*/, eCMD_light_ct_dw, NULL},
  {1962632111U/*灯光调冷*/, eCMD_light_ct_dw, NULL},
  {1473721626U/*灯冷一些*/, eCMD_light_ct_dw, NULL},
  {1473722803U/*灯冷一点*/, eCMD_light_ct_dw, NULL},
  {3742488657U/*色温最低*/, eCMD_light_ct_min, NULL},
  {3484489468U/*打开空调*/, eCMD_ac_on, NULL},
  {4052149644U/*开空调*/, eCMD_ac_on, NULL},
  {2543416495U/*关闭空调*/, eCMD_ac_off, NULL},
  {3971496319U/*请关闭空调*/, eCMD_ac_off, NULL},
  {704909206U/*关空调*/, eCMD_ac_off, NULL},
  {2778876352U/*调高一度*/, eCMD_ac_t_up, NULL},
  {1284536590U/*温度高一点*/, eCMD_ac_t_up, NULL},
  {1670886603U/*有点冷*/, eCMD_ac_t_up, NULL},
  {4246926815U/*调低一度*/, eCMD_ac_t_dw, NULL},
  {2752587053U/*温度低一点*/, eCMD_ac_t_dw, NULL},
  {1670888422U/*有点热*/, eCMD_ac_t_dw, NULL},
  {3923093124U/*空调风速调高一点*/, eCMD_ac_w_up, NULL},
  {783663565U/*空调风量调高一点*/, eCMD_ac_w_up, NULL},
  {1199842238U/*空调风调高一点*/, eCMD_ac_w_up, NULL},
  {952608368U/*空调风调大一点*/, eCMD_ac_w_up, NULL},
  {2384606861U/*风大一些*/, eCMD_ac_w_up, NULL},
  {1096176291U/*空调风速调低一点*/, eCMD_ac_w_dw, NULL},
  {2251714028U/*空调风量调低一点*/, eCMD_ac_w_dw, NULL},
  {2667892701U/*空调风调低一点*/, eCMD_ac_w_dw, NULL},
  {566244044U/*空调风调小一点*/, eCMD_ac_w_dw, NULL},
  {2769444382U/*安静一些*/, eCMD_ac_w_dw, NULL},
  {1550811541U/*空调风速调到最高*/, eCMD_ac_w_max, NULL},
  {1520752164U/*空调风速调到中风*/, eCMD_ac_t_middle, NULL},
  {1554952232U/*空调风速调到微风*/, eCMD_ac_t_min, NULL},
  {1550807284U/*空调风速调到最低*/, eCMD_ac_t_min, NULL},
  {189670108U/*制冷模式*/, eCMD_ac_m_cold, NULL},
  {2392353507U/*制冷*/, eCMD_ac_m_cold, NULL},
  {480409517U/*空调设为制冷模式*/, eCMD_ac_m_cold, NULL},
  {2390540958U/*冷风*/, eCMD_ac_m_cold, NULL},
  {3946129847U/*制热模式*/, eCMD_ac_m_hot, NULL},
  {2392355326U/*制热*/, eCMD_ac_m_hot, NULL},
  {4236869256U/*空调设为制热模式*/, eCMD_ac_m_hot, NULL},
  {2444730787U/*热风*/, eCMD_ac_m_hot, NULL},
  {2685685105U/*自动模式*/, eCMD_ac_m_auto, NULL},
  {2476960056U/*自动*/, eCMD_ac_m_auto, NULL},
  {2976424514U/*空调设为自动模式*/, eCMD_ac_m_auto, NULL},
  {3534892713U/*打开风扇*/, eCMD_fan_on, NULL},
  {1448864361U/*请开风扇*/, eCMD_fan_on, NULL},
  {4102552889U/*开风扇*/, eCMD_fan_on, NULL},
  {2701996303U/*把风扇打开*/, eCMD_fan_on, NULL},
  {2423654863U/*风扇启动*/, eCMD_fan_on, NULL},
  {2593819740U/*关闭风扇*/, eCMD_fan_off, NULL},
  {2396591219U/*请关风扇*/, eCMD_fan_off, NULL},
  {3721465907U/*关上风扇*/, eCMD_fan_off, NULL},
  {2409238059U/*风扇停止*/, eCMD_fan_off, NULL},
  {429500262U/*将风扇调高*/, eCMD_fan_w_up, NULL},
  {729834424U/*风量调高*/, eCMD_fan_w_up, NULL},
  {729830167U/*风量调低*/, eCMD_fan_w_dw, NULL},
  {2452016713U/*风扇摇头*/, eCMD_fan_s_on, NULL},
  {2451986922U/*风扇摆头*/, eCMD_fan_s_on, NULL},
  {955726356U/*停止摇头*/, eCMD_fan_s_off, NULL},
  {955696565U/*停止摆头*/, eCMD_fan_s_off, NULL},
  {3499918592U/*打开纱帘*/, eCMD_gauze_open, NULL},
  {2558845619U/*关闭纱帘*/, eCMD_gauze_close, NULL},
};

#endif
