
#reset
#set $psr=0xc0000000

##Load dsp
#download ihex verify=no $(ProjectPath)generated/dsp.hex

##Load imtb
#download ihex verify=no $(ProjectPath)generated/imtb.hex

##Load bmtb
#download ihex verify=no $(ProjectPath)generated/bmtb.hex

##Load bootloader binary
#download ihex verify=no $(ProjectPath)generated/boot.hex

##Load kv binary
#download ihex verify=no $(ProjectPath)generated/kv.hex

##Load yoc binary
#download ihex verify=no $(ProjectPath)generated/prim.hex

download ihex verify=no $(ProjectPath)generated/total_image.hex

