pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                powershell label: '', script: '''
                    scons
                '''    
            }
        }
        stage('Test') {
            options {
                timeout(time: 10, unit: 'MINUTES') 
            }
            steps {
                powershell label: '', script: '''

                '''
            }
        }
    }
    post {
        unsuccessful  {
            emailext body: '$DEFAULT_CONTENT' , subject: '$DEFAULT_SUBJECT' , to: 'jwzhang,mingzhou,xtzhang,weiyu,xwcai,lhyan,xgsong,zxguo'
        }
    }
}