##
 # Copyright (C) 2017-2024 Alibaba Group Holding Limited
 #
 # SPDX-License-Identifier: Apache-2.0
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
##

CUR_COMP_NAME := chip_riscv_dummy
CUR_COMP_DIR := $(TOP_DIR)/components/$(CUR_COMP_NAME)
# $(info come to $(CUR_COMP_DIR))

ifeq ($(COLLECT_BUILD_FILES), 0)
CFLAGS += -g -Wall
CFLAGS += -DCONFIG_CSI_V2=1 -DCONFIG_CSI="csi2"

ifeq ($(CPU_FULL_NAME), e901plusbm-cp)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=4096 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=4096 -DCONFIG_ARCH_INTERRUPTSTACK=4096 \
          -DCONFIG_SUPPORT_IRQ_NESTED=1 \
          -DCONFIG_XIP=1 \
          -DCONFIG_LIBC_MINI_PRINTF_SUPPORT=1
endif

ifeq ($(CPU_FULL_NAME), e901bzm-cp)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=4096 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=4096 -DCONFIG_ARCH_INTERRUPTSTACK=4096 \
          -DCONFIG_XIP=1 \
          -DCONFIG_LIBC_MINI_PRINTF_SUPPORT=1 \
          -D__ICACHE_PRESENT=0 -D__DCACHE_PRESENT=0
CFLAGS += -DCONFIG_MTVEC_MTVT_JVT_FLEXIBLE
# CFLAGS += -DCONFIG_TIMER_FOR_TICK
endif

ifeq ($(CPU_FULL_NAME), e902mt)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=4096 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=4096 -DCONFIG_ARCH_INTERRUPTSTACK=4096 \
          -DCONFIG_SUPPORT_IRQ_NESTED=1 \
          -DCONFIG_XIP=1 \
          -DCONFIG_LIBC_MINI_PRINTF_SUPPORT=1
endif

ifeq ($(CPU_FULL_NAME), e906fdp)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=4096 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=4096 -DCONFIG_ARCH_INTERRUPTSTACK=4096 \
          -DCONFIG_SUPPORT_IRQ_NESTED=1 \
          -DCONFIG_XIP=1 \
          -DCONFIG_LIBC_MINI_PRINTF_SUPPORT=1 \
          -DE906=y \
          -DCONFIG_CHECK_FPU_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), e907fdp)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=4096 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=4096 -DCONFIG_ARCH_INTERRUPTSTACK=4096 \
          -DCONFIG_SUPPORT_IRQ_NESTED=1 \
          -DCONFIG_XIP=1 \
          -DCONFIG_LIBC_MINI_PRINTF_SUPPORT=1 \
          -DE907 \
          -DCONFIG_CHECK_FPU_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), c906fdv)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), c907fdvm)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1 -DCONFIG_CHECK_MATRIX_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), c908v)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), c908x-cp-xt)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=32768 -DCONFIG_APP_TASK_STACK_SIZE=32768 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=32768 -DCONFIG_ARCH_INTERRUPTSTACK=32768 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1 \
          -DCONFIG_USE_FASTMEM=1 -DCONFIG_FASTMEM_ADDR=0x50400000 -DCONFIG_FASTMEM_SIZE=0x200000
CFLAGS += -DSTATIC_CSK_CPU_STACK_EXTRAL=32768
# CFLAGS += -DCONFIG_CPU_FREQ_HZ=14810000
CFLAGS += -DCONFIG_CPU_FREQ_HZ=11000000
endif

ifeq ($(CPU_FULL_NAME), c920v2)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), c920v3-cp-xt)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), r908fdv-cp-xt)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 -DCONFIG_CLIC_BASE=0x0c010000 \
          -DCONFIG_INTC_CLIC_PLIC=1 -DCONFIG_SUPPORT_IRQ_NESTED=1 \
          -DCONFIG_FPP_ENABLE=0 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), r910)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1
endif

ifeq ($(CPU_FULL_NAME), r920)
CFLAGS += -DCONFIG_INIT_TASK_STACK_SIZE=8192 -DCONFIG_APP_TASK_STACK_SIZE=8192 \
          -DCONFIG_SUPPORT_TSPEND=1 -DCONFIG_ARCH_MAINSTACK=8192 -DCONFIG_ARCH_INTERRUPTSTACK=8192 \
          -DCONFIG_VIC_TSPDR=0x0c000000 -DCONFIG_PLIC_BASE=0x08000000 \
          -DCONFIG_CHECK_FPU_DIRTY=1 -DCONFIG_CHECK_VECTOR_DIRTY=1
endif

else
$(CUR_COMP_NAME)_incs := $(CUR_COMP_DIR)/include $(CUR_COMP_DIR)/include/asm

$(CUR_COMP_NAME)_c_srcs := 	$(wildcard $(CUR_COMP_DIR)/src/arch/$(CPU_FULL_NAME)/*.c) \
                            $(wildcard $(CUR_COMP_DIR)/src/sys/*.c) \
                            $(CUR_COMP_DIR)/src/drivers/clk.c \
                            $(CUR_COMP_DIR)/src/drivers/dma.c \
                            $(CUR_COMP_DIR)/src/drivers/dw_uart_ll.c \
                            $(CUR_COMP_DIR)/src/drivers/gpio.c \
                            $(CUR_COMP_DIR)/src/drivers/gpio_pin.c \
                            $(CUR_COMP_DIR)/src/drivers/pinmux.c \
                            $(CUR_COMP_DIR)/src/drivers/power_manage.c \
                            $(CUR_COMP_DIR)/src/drivers/timer.c \
                            $(CUR_COMP_DIR)/src/drivers/uart.c

$(CUR_COMP_NAME)_asm_srcs := $(wildcard $(CUR_COMP_DIR)/src/arch/$(CPU_FULL_NAME)/*.S)
endif
