#ifndef PWM_CONFIG_H_
#define PWM_CONFIG_H_
#include "io_config.h"


#define PWM0_FUNC AF_ADTIM1_CH1
#define PWM1_FUNC AF_ADTIM1_CH2
#define PWM2_FUNC AF_ADTIM1_CH3
#define PWM3_FUNC AF_ADTIM1_CH4
#define PWM4_FUNC AF_GPTIMA1_CH1
#define PWM5_FUNC AF_GPTIMA1_CH2
#define PWM6_FUNC AF_GPTIMA1_CH3
#define PWM7_FUNC AF_GPTIMA1_CH4
#define PWM8_FUNC AF_GPTIMB1_CH1
#define PWM9_FUNC AF_GPTIMB1_CH2
#define PWM10_FUNC AF_GPTIMB1_CH3
#define PWM11_FUNC AF_GPTIMB1_CH4
#define PWM12_FUNC AF_GPTIMC1_CH1
#define PWM13_FUNC AF_GPTIMC1_CH2

#endif
